// ==================== data.js ====================
// ПОЛНАЯ БАЗА HSK 1 + HSK 2 + HSK 3 + HSK 4 СО ВСЕМИ ЭМОДЗИ

const HSK_DATA = {
  // ========== HSK 1 ==========
  hsk1: {
    label: 'HSK 1',
    decks: [
      {
        id: 1,
        emoji: '❓',
        title: 'Вопросы и местоимения',
        cls: 'dc1',
        words: [
          { hanzi: '我', pinyin: 'wǒ', ru: 'Я', em: '👤' },
          { hanzi: '我们', pinyin: 'wǒmen', ru: 'Мы', em: '👥' },
          { hanzi: '你', pinyin: 'nǐ', ru: 'Ты', em: '🫵' },
          { hanzi: '您', pinyin: 'nín', ru: 'Вы (вежл.)', em: '🙏' },
          { hanzi: '他', pinyin: 'tā', ru: 'Он', em: '👨' },
          { hanzi: '她', pinyin: 'tā', ru: 'Она', em: '👩' },
          { hanzi: '这', pinyin: 'zhè', ru: 'Этот', em: '👈' },
          { hanzi: '那', pinyin: 'nà', ru: 'Тот', em: '👉' },
          { hanzi: '哪', pinyin: 'nǎ', ru: 'Какой', em: '🤔' },
          { hanzi: '谁', pinyin: 'shéi', ru: 'Кто', em: '🙋' },
          { hanzi: '什么', pinyin: 'shénme', ru: 'Что', em: '❓' },
          { hanzi: '多少', pinyin: 'duōshao', ru: 'Сколько', em: '🔢' },
          { hanzi: '几', pinyin: 'jǐ', ru: 'Сколько (небольшое)', em: '🤏' },
          { hanzi: '怎么', pinyin: 'zěnme', ru: 'Как', em: '🔄' },
          { hanzi: '怎么样', pinyin: 'zěnmeyàng', ru: 'Как дела', em: '💬' }
        ]
      },
      {
        id: 2,
        emoji: '🔢',
        title: 'Числа и счётные слова',
        cls: 'dc2',
        words: [
          { hanzi: '一', pinyin: 'yī', ru: 'Один', em: '1️⃣' },
          { hanzi: '二', pinyin: 'èr', ru: 'Два', em: '2️⃣' },
          { hanzi: '三', pinyin: 'sān', ru: 'Три', em: '3️⃣' },
          { hanzi: '四', pinyin: 'sì', ru: 'Четыре', em: '4️⃣' },
          { hanzi: '五', pinyin: 'wǔ', ru: 'Пять', em: '5️⃣' },
          { hanzi: '六', pinyin: 'liù', ru: 'Шесть', em: '6️⃣' },
          { hanzi: '七', pinyin: 'qī', ru: 'Семь', em: '7️⃣' },
          { hanzi: '八', pinyin: 'bā', ru: 'Восемь', em: '8️⃣' },
          { hanzi: '九', pinyin: 'jiǔ', ru: 'Девять', em: '9️⃣' },
          { hanzi: '十', pinyin: 'shí', ru: 'Десять', em: '🔟' },
          { hanzi: '零', pinyin: 'líng', ru: 'Ноль', em: '0️⃣' },
          { hanzi: '百', pinyin: 'bǎi', ru: 'Сто', em: '💯' },
          { hanzi: '千', pinyin: 'qiān', ru: 'Тысяча', em: '💯' },
          { hanzi: '万', pinyin: 'wàn', ru: 'Десять тысяч', em: '💯' },
          { hanzi: '个', pinyin: 'gè', ru: 'Счётное слово (общее)', em: '📦' },
          { hanzi: '岁', pinyin: 'suì', ru: 'Лет (возраст)', em: '🎂' },
          { hanzi: '本', pinyin: 'běn', ru: 'Счётное для книг', em: '📚' },
          { hanzi: '块', pinyin: 'kuài', ru: 'Юань (деньги)', em: '🪙' },
          { hanzi: '两', pinyin: 'liǎng', ru: 'Два (счётное)', em: '2️⃣' }
        ]
      },
      {
        id: 3,
        emoji: '🔤',
        title: 'Служебные слова и наречия',
        cls: 'dc3',
        words: [
          { hanzi: '不', pinyin: 'bù', ru: 'Не', em: '🚫' },
          { hanzi: '没', pinyin: 'méi', ru: 'Нет (отрицание)', em: '❌' },
          { hanzi: '很', pinyin: 'hěn', ru: 'Очень', em: '💪' },
          { hanzi: '太', pinyin: 'tài', ru: 'Слишком', em: '😤' },
          { hanzi: '都', pinyin: 'dōu', ru: 'Все', em: '👫' },
          { hanzi: '也', pinyin: 'yě', ru: 'Тоже', em: '➕' },
          { hanzi: '再', pinyin: 'zài', ru: 'Снова', em: '🔄' },
          { hanzi: '和', pinyin: 'hé', ru: 'И (союз)', em: '🤝' },
          { hanzi: '在', pinyin: 'zài', ru: 'В (предлог)', em: '📍' },
          { hanzi: '的', pinyin: 'de', ru: 'Притяжательная частица', em: '🔗' },
          { hanzi: '了', pinyin: 'le', ru: 'Частица завершения', em: '✅' },
          { hanzi: '吗', pinyin: 'ma', ru: 'Вопросительная частица', em: '❓' },
          { hanzi: '呢', pinyin: 'ne', ru: 'Вопросительная частица', em: '🤷' },
          { hanzi: '一点儿', pinyin: 'yīdiǎnr', ru: 'Немного', em: '🤏' }
        ]
      },
      {
        id: 4,
        emoji: '📍',
        title: 'Места и направления',
        cls: 'dc4',
        words: [
          { hanzi: '家', pinyin: 'jiā', ru: 'Дом', em: '🏠' },
          { hanzi: '学校', pinyin: 'xuéxiào', ru: 'Школа', em: '🏫' },
          { hanzi: '饭店', pinyin: 'fàndiàn', ru: 'Ресторан', em: '🍽️' },
          { hanzi: '商店', pinyin: 'shāngdiàn', ru: 'Магазин', em: '🛒' },
          { hanzi: '医院', pinyin: 'yīyuàn', ru: 'Больница', em: '🏥' },
          { hanzi: '中国', pinyin: 'Zhōngguó', ru: 'Китай', em: '🏮' },
          { hanzi: '北京', pinyin: 'Běijīng', ru: 'Пекин', em: '🏯' },
          { hanzi: '上', pinyin: 'shàng', ru: 'На, сверху', em: '⬆️' },
          { hanzi: '下', pinyin: 'xià', ru: 'Под, снизу', em: '⬇️' },
          { hanzi: '前面', pinyin: 'qiánmiàn', ru: 'Впереди', em: '🔜' },
          { hanzi: '后面', pinyin: 'hòumiàn', ru: 'Позади', em: '🔙' },
          { hanzi: '里面', pinyin: 'lǐmiàn', ru: 'Внутри', em: '🔲' },
          { hanzi: '外面', pinyin: 'wàimiàn', ru: 'Снаружи', em: '🚪' },
          { hanzi: '旁边', pinyin: 'pángbiān', ru: 'Рядом', em: '👥' }
        ]
      },
      {
        id: 5,
        emoji: '🕐',
        title: 'Время и даты',
        cls: 'dc5',
        words: [
          { hanzi: '今天', pinyin: 'jīntiān', ru: 'Сегодня', em: '📅' },
          { hanzi: '明天', pinyin: 'míngtiān', ru: 'Завтра', em: '🔮' },
          { hanzi: '昨天', pinyin: 'zuótiān', ru: 'Вчера', em: '⏪' },
          { hanzi: '上午', pinyin: 'shàngwǔ', ru: 'Утро (до полудня)', em: '🌅' },
          { hanzi: '中午', pinyin: 'zhōngwǔ', ru: 'Полдень', em: '☀️' },
          { hanzi: '下午', pinyin: 'xiàwǔ', ru: 'После обеда', em: '🌇' },
          { hanzi: '年', pinyin: 'nián', ru: 'Год', em: '📆' },
          { hanzi: '月', pinyin: 'yuè', ru: 'Месяц', em: '🗓️' },
          { hanzi: '号', pinyin: 'hào', ru: 'Число (день)', em: '🔢' },
          { hanzi: '星期', pinyin: 'xīngqī', ru: 'Неделя', em: '📅' },
          { hanzi: '点', pinyin: 'diǎn', ru: 'Час', em: '🕐' },
          { hanzi: '分钟', pinyin: 'fēnzhōng', ru: 'Минута', em: '⏱️' },
          { hanzi: '现在', pinyin: 'xiànzài', ru: 'Сейчас', em: '⏰' },
          { hanzi: '时候', pinyin: 'shíhou', ru: 'Время (момент)', em: '⏳' },
          { hanzi: '小时', pinyin: 'xiǎoshí', ru: 'Час (длительность)', em: '🕐' }
        ]
      },
      {
        id: 6,
        emoji: '👨‍👩‍👧',
        title: 'Семья и люди',
        cls: 'dc6',
        words: [
          { hanzi: '爸爸', pinyin: 'bàba', ru: 'Папа', em: '👨' },
          { hanzi: '妈妈', pinyin: 'māma', ru: 'Мама', em: '👩' },
          { hanzi: '儿子', pinyin: 'érzi', ru: 'Сын', em: '👦' },
          { hanzi: '女儿', pinyin: 'nǚ\'ér', ru: 'Дочь', em: '👧' },
          { hanzi: '老师', pinyin: 'lǎoshī', ru: 'Учитель', em: '📖' },
          { hanzi: '学生', pinyin: 'xuésheng', ru: 'Ученик', em: '🎓' },
          { hanzi: '同学', pinyin: 'tóngxué', ru: 'Одноклассник', em: '🎓' },
          { hanzi: '朋友', pinyin: 'péngyou', ru: 'Друг', em: '🤝' },
          { hanzi: '医生', pinyin: 'yīshēng', ru: 'Врач', em: '🏥' },
          { hanzi: '先生', pinyin: 'xiānsheng', ru: 'Господин', em: '🤵' },
          { hanzi: '小姐', pinyin: 'xiǎojiě', ru: 'Госпожа', em: '👩' },
          { hanzi: '人', pinyin: 'rén', ru: 'Человек', em: '🧑' },
          { hanzi: '名字', pinyin: 'míngzi', ru: 'Имя', em: '🏷️' }
        ]
      },
      {
        id: 7,
        emoji: '🍽️',
        title: 'Еда и напитки',
        cls: 'dc7',
        words: [
          { hanzi: '米饭', pinyin: 'mǐfàn', ru: 'Рис (варёный)', em: '🍚' },
          { hanzi: '水果', pinyin: 'shuǐguǒ', ru: 'Фрукты', em: '🍇' },
          { hanzi: '苹果', pinyin: 'píngguǒ', ru: 'Яблоко', em: '🍎' },
          { hanzi: '菜', pinyin: 'cài', ru: 'Блюдо', em: '🥬' },
          { hanzi: '茶', pinyin: 'chá', ru: 'Чай', em: '🍵' },
          { hanzi: '水', pinyin: 'shuǐ', ru: 'Вода', em: '💧' },
          { hanzi: '牛奶', pinyin: 'niúnǎi', ru: 'Молоко', em: '🥛' },
          { hanzi: '面包', pinyin: 'miànbāo', ru: 'Хлеб', em: '🍞' },
          { hanzi: '鸡蛋', pinyin: 'jīdàn', ru: 'Яйцо', em: '🥚' }
        ]
      },
      {
        id: 8,
        emoji: '📦',
        title: 'Предметы и вещи',
        cls: 'dc8',
        words: [
          { hanzi: '杯子', pinyin: 'bēizi', ru: 'Стакан', em: '🥤' },
          { hanzi: '钱', pinyin: 'qián', ru: 'Деньги', em: '💰' },
          { hanzi: '飞机', pinyin: 'fēijī', ru: 'Самолёт', em: '✈️' },
          { hanzi: '衣服', pinyin: 'yīfu', ru: 'Одежда', em: '👕' },
          { hanzi: '东西', pinyin: 'dōngxi', ru: 'Вещь', em: '📦' },
          { hanzi: '书', pinyin: 'shū', ru: 'Книга', em: '📖' },
          { hanzi: '字', pinyin: 'zì', ru: 'Иероглиф', em: '✍️' },
          { hanzi: '桌子', pinyin: 'zhuōzi', ru: 'Стол', em: '🪑' },
          { hanzi: '椅子', pinyin: 'yǐzi', ru: 'Стул', em: '💺' },
          { hanzi: '电视', pinyin: 'diànshì', ru: 'Телевизор', em: '📺' },
          { hanzi: '电脑', pinyin: 'diànnǎo', ru: 'Компьютер', em: '💻' },
          { hanzi: '手机', pinyin: 'shǒujī', ru: 'Телефон', em: '📱' }
        ]
      },
      {
        id: 9,
        emoji: '🗣️',
        title: 'Общение и этикет',
        cls: 'dc9',
        words: [
          { hanzi: '谢谢', pinyin: 'xièxie', ru: 'Спасибо', em: '🙏' },
          { hanzi: '不客气', pinyin: 'búkèqi', ru: 'Не за что', em: '😊' },
          { hanzi: '再见', pinyin: 'zàijiàn', ru: 'До свидания', em: '👋' },
          { hanzi: '请', pinyin: 'qǐng', ru: 'Пожалуйста', em: '🙏' },
          { hanzi: '对不起', pinyin: 'duìbuqǐ', ru: 'Извините', em: '😔' },
          { hanzi: '没关系', pinyin: 'méiguānxi', ru: 'Ничего', em: '👌' },
          { hanzi: '喂', pinyin: 'wèi', ru: 'Алло', em: '📞' },
          { hanzi: '叫', pinyin: 'jiào', ru: 'Зваться', em: '📛' }
        ]
      },
      {
        id: 10,
        emoji: '🏃',
        title: 'Глаголы действия',
        cls: 'dc10',
        words: [
          { hanzi: '是', pinyin: 'shì', ru: 'Быть', em: '✅' },
          { hanzi: '有', pinyin: 'yǒu', ru: 'Иметь', em: '🤲' },
          { hanzi: '看', pinyin: 'kàn', ru: 'Смотреть', em: '👀' },
          { hanzi: '听', pinyin: 'tīng', ru: 'Слушать', em: '👂' },
          { hanzi: '说', pinyin: 'shuō', ru: 'Говорить', em: '🗣️' },
          { hanzi: '读', pinyin: 'dú', ru: 'Читать', em: '📖' },
          { hanzi: '写', pinyin: 'xiě', ru: 'Писать', em: '✍️' },
          { hanzi: '看见', pinyin: 'kànjiàn', ru: 'Увидеть', em: '👁️' },
          { hanzi: '来', pinyin: 'lái', ru: 'Приходить', em: '🚶' },
          { hanzi: '去', pinyin: 'qù', ru: 'Идти', em: '🚀' },
          { hanzi: '回', pinyin: 'huí', ru: 'Возвращаться', em: '🔙' },
          { hanzi: '吃', pinyin: 'chī', ru: 'Есть', em: '🍜' },
          { hanzi: '喝', pinyin: 'hē', ru: 'Пить', em: '🥤' },
          { hanzi: '睡觉', pinyin: 'shuìjiào', ru: 'Спать', em: '😴' },
          { hanzi: '打电话', pinyin: 'dǎdiànhuà', ru: 'Звонить', em: '📞' },
          { hanzi: '做', pinyin: 'zuò', ru: 'Делать', em: '🔨' },
          { hanzi: '买', pinyin: 'mǎi', ru: 'Покупать', em: '🛍️' },
          { hanzi: '开', pinyin: 'kāi', ru: 'Открывать', em: '🔓' },
          { hanzi: '坐', pinyin: 'zuò', ru: 'Сидеть', em: '🪑' },
          { hanzi: '住', pinyin: 'zhù', ru: 'Жить', em: '🏠' },
          { hanzi: '学习', pinyin: 'xuéxí', ru: 'Учиться', em: '📚' },
          { hanzi: '工作', pinyin: 'gōngzuò', ru: 'Работать', em: '💼' },
          { hanzi: '下雨', pinyin: 'xiàyǔ', ru: 'Дождь (идёт)', em: '🌧️' }
        ]
      },
      {
        id: 11,
        emoji: '💖',
        title: 'Чувства и прилагательные',
        cls: 'dc11',
        words: [
          { hanzi: '爱', pinyin: 'ài', ru: 'Любить', em: '❤️' },
          { hanzi: '喜欢', pinyin: 'xǐhuan', ru: 'Нравиться', em: '😍' },
          { hanzi: '想', pinyin: 'xiǎng', ru: 'Хотеть', em: '💭' },
          { hanzi: '认识', pinyin: 'rènshi', ru: 'Знать (быть знакомым)', em: '🤝' },
          { hanzi: '会', pinyin: 'huì', ru: 'Уметь', em: '🎯' },
          { hanzi: '能', pinyin: 'néng', ru: 'Мочь', em: '💪' },
          { hanzi: '好', pinyin: 'hǎo', ru: 'Хороший', em: '👍' },
          { hanzi: '大', pinyin: 'dà', ru: 'Большой', em: '🐘' },
          { hanzi: '小', pinyin: 'xiǎo', ru: 'Маленький', em: '🐜' },
          { hanzi: '多', pinyin: 'duō', ru: 'Много', em: '📚' },
          { hanzi: '少', pinyin: 'shǎo', ru: 'Мало', em: '🤏' },
          { hanzi: '冷', pinyin: 'lěng', ru: 'Холодный', em: '🥶' },
          { hanzi: '热', pinyin: 'rè', ru: 'Горячий', em: '🥵' },
          { hanzi: '高兴', pinyin: 'gāoxìng', ru: 'Радостный', em: '😄' },
          { hanzi: '漂亮', pinyin: 'piàoliang', ru: 'Красивый', em: '✨' }
        ]
      }
    ]
  },

  // ========== HSK 2 ==========
  hsk2: {
    label: 'HSK 2',
    decks: [
      {
        id: 1,
        emoji: '👤',
        title: 'Семья и люди',
        cls: 'dc1',
        words: [
          { hanzi: '大家', pinyin: 'dàjiā', ru: 'Все', em: '👥' },
          { hanzi: '弟弟', pinyin: 'dìdi', ru: 'Младший брат', em: '👦' },
          { hanzi: '哥哥', pinyin: 'gēge', ru: 'Старший брат', em: '👦' },
          { hanzi: '姐姐', pinyin: 'jiějie', ru: 'Старшая сестра', em: '👩' },
          { hanzi: '妹妹', pinyin: 'mèimei', ru: 'Младшая сестра', em: '👩' },
          { hanzi: '妻子', pinyin: 'qīzi', ru: 'Жена', em: '👰' },
          { hanzi: '丈夫', pinyin: 'zhàngfu', ru: 'Муж', em: '👨' },
          { hanzi: '孩子', pinyin: 'háizi', ru: 'Ребёнок', em: '👶' },
          { hanzi: '男', pinyin: 'nán', ru: 'Мужской', em: '👨' },
          { hanzi: '女', pinyin: 'nǚ', ru: 'Женский', em: '👩' },
          { hanzi: '服务员', pinyin: 'fúwùyuán', ru: 'Официант', em: '👨‍🍳' }
        ]
      },
      {
        id: 2,
        emoji: '🏠',
        title: 'Дом и предметы',
        cls: 'dc2',
        words: [
          { hanzi: '房间', pinyin: 'fángjiān', ru: 'Комната', em: '🚪' },
          { hanzi: '门', pinyin: 'mén', ru: 'Дверь', em: '🚪' },
          { hanzi: '手表', pinyin: 'shǒubiǎo', ru: 'Часы (наручные)', em: '⌚' },
          { hanzi: '报纸', pinyin: 'bàozhǐ', ru: 'Газета', em: '📰' },
          { hanzi: '铅笔', pinyin: 'qiānbǐ', ru: 'Карандаш', em: '✏️' },
          { hanzi: '票', pinyin: 'piào', ru: 'Билет', em: '🎫' },
          { hanzi: '颜色', pinyin: 'yánsè', ru: 'Цвет', em: '🎨' },
          { hanzi: '眼睛', pinyin: 'yǎnjing', ru: 'Глаза', em: '👀' },
          { hanzi: '身体', pinyin: 'shēntǐ', ru: 'Тело', em: '🧍' },
          { hanzi: '药', pinyin: 'yào', ru: 'Лекарство', em: '💊' }
        ]
      },
      {
        id: 3,
        emoji: '🍽️',
        title: 'Еда и вкусы',
        cls: 'dc3',
        words: [
          { hanzi: '面条', pinyin: 'miàntiáo', ru: 'Лапша', em: '🍜' },
          { hanzi: '羊肉', pinyin: 'yángròu', ru: 'Баранина', em: '🍖' },
          { hanzi: '西瓜', pinyin: 'xīguā', ru: 'Арбуз', em: '🍉' },
          { hanzi: '鱼', pinyin: 'yú', ru: 'Рыба', em: '🐟' },
          { hanzi: '咖啡', pinyin: 'kāfēi', ru: 'Кофе', em: '☕' },
          { hanzi: '好吃', pinyin: 'hǎochī', ru: 'Вкусный', em: '😋' },
          { hanzi: '便宜', pinyin: 'piányi', ru: 'Дешёвый', em: '💰' },
          { hanzi: '贵', pinyin: 'guì', ru: 'Дорогой', em: '💰' }
        ]
      },
      {
        id: 4,
        emoji: '🏃',
        title: 'Прилагательные (состояние)',
        cls: 'dc4',
        words: [
          { hanzi: '快', pinyin: 'kuài', ru: 'Быстрый', em: '🏃' },
          { hanzi: '慢', pinyin: 'màn', ru: 'Медленный', em: '🐢' },
          { hanzi: '忙', pinyin: 'máng', ru: 'Занятый', em: '🏃' },
          { hanzi: '高', pinyin: 'gāo', ru: 'Высокий', em: '📈' },
          { hanzi: '新', pinyin: 'xīn', ru: 'Новый', em: '🆕' },
          { hanzi: '长', pinyin: 'cháng', ru: 'Длинный', em: '📏' },
          { hanzi: '白', pinyin: 'bái', ru: 'Белый', em: '⬜' },
          { hanzi: '黑', pinyin: 'hēi', ru: 'Чёрный', em: '⬛' },
          { hanzi: '红', pinyin: 'hóng', ru: 'Красный', em: '🟥' }
        ]
      },
      {
        id: 5,
        emoji: '🚗',
        title: 'Транспорт и направления',
        cls: 'dc5',
        words: [
          { hanzi: '公共汽车', pinyin: 'gōnggòng qìchē', ru: 'Автобус', em: '🚌' },
          { hanzi: '火车站', pinyin: 'huǒchēzhàn', ru: 'Вокзал', em: '🚉' },
          { hanzi: '机场', pinyin: 'jīchǎng', ru: 'Аэропорт', em: '🛫' },
          { hanzi: '路', pinyin: 'lù', ru: 'Дорога', em: '🛣️' },
          { hanzi: '左边', pinyin: 'zuǒbiān', ru: 'Слева', em: '👈' },
          { hanzi: '右边', pinyin: 'yòubiān', ru: 'Справа', em: '👉' },
          { hanzi: '旁边', pinyin: 'pángbiān', ru: 'Рядом', em: '👥' },
          { hanzi: '外', pinyin: 'wài', ru: 'Снаружи', em: '🚪' },
          { hanzi: '往', pinyin: 'wǎng', ru: 'В сторону', em: '➡️' },
          { hanzi: '远', pinyin: 'yuǎn', ru: 'Далеко', em: '📏' },
          { hanzi: '进', pinyin: 'jìn', ru: 'Входить', em: '🚪' },
          { hanzi: '出', pinyin: 'chū', ru: 'Выходить', em: '🚪' },
          { hanzi: '到', pinyin: 'dào', ru: 'До', em: '📍' },
          { hanzi: '从', pinyin: 'cóng', ru: 'Из', em: '➡️' }
        ]
      },
      {
        id: 6,
        emoji: '🕐',
        title: 'Время и наречия',
        cls: 'dc6',
        words: [
          { hanzi: '早上', pinyin: 'zǎoshang', ru: 'Утро', em: '🌅' },
          { hanzi: '晚上', pinyin: 'wǎnshang', ru: 'Вечер', em: '🌆' },
          { hanzi: '时间', pinyin: 'shíjiān', ru: 'Время', em: '⏰' },
          { hanzi: '去年', pinyin: 'qùnián', ru: 'В прошлом году', em: '📅' },
          { hanzi: '日', pinyin: 'rì', ru: 'День', em: '☀️' },
          { hanzi: '生日', pinyin: 'shēngrì', ru: 'День рождения', em: '🎂' },
          { hanzi: '第一', pinyin: 'dì-yī', ru: 'Первый', em: '🥇' },
          { hanzi: '次', pinyin: 'cì', ru: 'Раз', em: '🔢' },
          { hanzi: '每', pinyin: 'měi', ru: 'Каждый', em: '📅' },
          { hanzi: '已经', pinyin: 'yǐjīng', ru: 'Уже', em: '✅' },
          { hanzi: '正在', pinyin: 'zhèngzài', ru: 'Сейчас (в процессе)', em: '⏰' },
          { hanzi: '就', pinyin: 'jiù', ru: 'Тогда, сразу', em: '⏰' },
          { hanzi: '还', pinyin: 'hái', ru: 'Ещё', em: '🔄' }
        ]
      },
      {
        id: 7,
        emoji: '🏃',
        title: 'Спорт и активность',
        cls: 'dc7',
        words: [
          { hanzi: '打篮球', pinyin: 'dǎ lánqiú', ru: 'Играть в баскетбол', em: '🏀' },
          { hanzi: '踢足球', pinyin: 'tī zúqiú', ru: 'Играть в футбол', em: '⚽' },
          { hanzi: '跑步', pinyin: 'pǎobù', ru: 'Бегать', em: '🏃' },
          { hanzi: '游泳', pinyin: 'yóuyǒng', ru: 'Плавать', em: '🏊' },
          { hanzi: '跳舞', pinyin: 'tiàowǔ', ru: 'Танцевать', em: '💃' },
          { hanzi: '唱歌', pinyin: 'chànggē', ru: 'Петь', em: '🎤' },
          { hanzi: '运动', pinyin: 'yùndòng', ru: 'Спорт', em: '🏃' },
          { hanzi: '玩', pinyin: 'wán', ru: 'Играть', em: '🎮' },
          { hanzi: '休息', pinyin: 'xiūxi', ru: 'Отдыхать', em: '😌' },
          { hanzi: '起床', pinyin: 'qǐchuáng', ru: 'Вставать', em: '🛏️' }
        ]
      },
      {
        id: 8,
        emoji: '💼',
        title: 'Работа и учёба',
        cls: 'dc8',
        words: [
          { hanzi: '上班', pinyin: 'shàngbān', ru: 'Идти на работу', em: '💼' },
          { hanzi: '考试', pinyin: 'kǎoshì', ru: 'Экзамен', em: '📝' },
          { hanzi: '开始', pinyin: 'kāishǐ', ru: 'Начинать', em: '▶️' },
          { hanzi: '准备', pinyin: 'zhǔnbèi', ru: 'Готовиться', em: '📋' },
          { hanzi: '希望', pinyin: 'xīwàng', ru: 'Надеяться', em: '💫' },
          { hanzi: '公司', pinyin: 'gōngsī', ru: 'Компания', em: '🏢' },
          { hanzi: '教室', pinyin: 'jiàoshì', ru: 'Класс', em: '🏫' },
          { hanzi: '宾馆', pinyin: 'bīnguǎn', ru: 'Гостиница', em: '🏨' },
          { hanzi: '事情', pinyin: 'shìqing', ru: 'Дело', em: '📋' },
          { hanzi: '帮助', pinyin: 'bāngzhù', ru: 'Помогать', em: '🤝' },
          { hanzi: '卖', pinyin: 'mài', ru: 'Продавать', em: '💲' },
          { hanzi: '比', pinyin: 'bǐ', ru: 'Чем (сравнение)', em: '⚖️' },
          { hanzi: '对', pinyin: 'duì', ru: 'Правильно', em: '✅' },
          { hanzi: '错', pinyin: 'cuò', ru: 'Неправильно', em: '❌' },
          { hanzi: '可以', pinyin: 'kěyǐ', ru: 'Можно', em: '✅' },
          { hanzi: '得', pinyin: 'de', ru: 'Частица (способ)', em: '🔗' },
          { hanzi: '过', pinyin: 'guò', ru: 'Проходить (опыт)', em: '➡️' }
        ]
      },
      {
        id: 9,
        emoji: '💬',
        title: 'Общение и глаголы',
        cls: 'dc9',
        words: [
          { hanzi: '说话', pinyin: 'shuōhuà', ru: 'Говорить', em: '🗣️' },
          { hanzi: '介绍', pinyin: 'jièshào', ru: 'Представлять', em: '🤝' },
          { hanzi: '告诉', pinyin: 'gàosu', ru: 'Сообщать', em: '📢' },
          { hanzi: '问', pinyin: 'wèn', ru: 'Спрашивать', em: '❓' },
          { hanzi: '问题', pinyin: 'wèntí', ru: 'Вопрос', em: '❓' },
          { hanzi: '意思', pinyin: 'yìsi', ru: 'Значение', em: '💡' },
          { hanzi: '知道', pinyin: 'zhīdào', ru: 'Знать', em: '🧠' },
          { hanzi: '觉得', pinyin: 'juéde', ru: 'Чувствовать', em: '💭' },
          { hanzi: '懂', pinyin: 'dǒng', ru: 'Понимать', em: '🧠' },
          { hanzi: '让', pinyin: 'ràng', ru: 'Позволять', em: '👍' },
          { hanzi: '送', pinyin: 'sòng', ru: 'Провожать', em: '🚶' },
          { hanzi: '找', pinyin: 'zhǎo', ru: 'Искать', em: '🔍' },
          { hanzi: '走', pinyin: 'zǒu', ru: 'Идти', em: '🚶' },
          { hanzi: '等', pinyin: 'děng', ru: 'Ждать', em: '⏳' },
          { hanzi: '完', pinyin: 'wán', ru: 'Заканчивать', em: '✅' }
        ]
      },
      {
        id: 10,
        emoji: '💖',
        title: 'Чувства и эмоции',
        cls: 'dc10',
        words: [
          { hanzi: '快乐', pinyin: 'kuàilè', ru: 'Счастливый', em: '😊' },
          { hanzi: '笑', pinyin: 'xiào', ru: 'Смеяться', em: '😄' },
          { hanzi: '爱', pinyin: 'ài', ru: 'Любить', em: '❤️' },
          { hanzi: '想', pinyin: 'xiǎng', ru: 'Хотеть', em: '💭' },
          { hanzi: '要', pinyin: 'yào', ru: 'Хотеть', em: '💭' },
          { hanzi: '生病', pinyin: 'shēngbìng', ru: 'Болеть', em: '🤒' },
          { hanzi: '累', pinyin: 'lèi', ru: 'Усталый', em: '😫' },
          { hanzi: '别', pinyin: 'bié', ru: 'Не (запрет)', em: '🚫' },
          { hanzi: '吧', pinyin: 'ba', ru: 'Частица (предложение)', em: '💬' },
          { hanzi: '虽然', pinyin: 'suīrán', ru: 'Хотя', em: '🤔' },
          { hanzi: '最', pinyin: 'zuì', ru: 'Самый', em: '🥇' },
          { hanzi: '真', pinyin: 'zhēn', ru: 'Действительно', em: '💯' },
          { hanzi: '非常', pinyin: 'fēicháng', ru: 'Очень', em: '💪' },
          { hanzi: '可能', pinyin: 'kěnéng', ru: 'Может быть', em: '🤷' },
          { hanzi: '雪', pinyin: 'xuě', ru: 'Снег', em: '❄️' },
          { hanzi: '晴', pinyin: 'qíng', ru: 'Ясный', em: '☀️' },
          { hanzi: '阴', pinyin: 'yīn', ru: 'Пасмурный', em: '☁️' }
        ]
      }
    ]
  },

  // ========== HSK 3 ==========
  hsk3: {
    label: 'HSK 3',
    decks: [
      {
        id: 1,
        emoji: '👨‍👩‍👧',
        title: 'Семья и люди',
        cls: 'dc1',
        words: [
          { hanzi: '阿姨', pinyin: 'āyí', ru: 'Тётя', em: '👩' },
          { hanzi: '奶奶', pinyin: 'nǎinai', ru: 'Бабушка', em: '👵' },
          { hanzi: '爷爷', pinyin: 'yéye', ru: 'Дедушка', em: '👴' },
          { hanzi: '叔叔', pinyin: 'shūshu', ru: 'Дядя', em: '👨' },
          { hanzi: '邻居', pinyin: 'línjū', ru: 'Сосед', em: '👥' },
          { hanzi: '客人', pinyin: 'kèrén', ru: 'Гость', em: '🤝' },
          { hanzi: '经理', pinyin: 'jīnglǐ', ru: 'Менеджер', em: '💼' },
          { hanzi: '校长', pinyin: 'xiàozhǎng', ru: 'Директор', em: '👨‍🏫' },
          { hanzi: '同事', pinyin: 'tóngshì', ru: 'Коллега', em: '👥' }
        ]
      },
      {
        id: 2,
        emoji: '🏠',
        title: 'Дом и быт',
        cls: 'dc2',
        words: [
          { hanzi: '冰箱', pinyin: 'bīngxiāng', ru: 'Холодильник', em: '🧊' },
          { hanzi: '空调', pinyin: 'kōngtiáo', ru: 'Кондиционер', em: '❄️' },
          { hanzi: '电梯', pinyin: 'diàntī', ru: 'Лифт', em: '🛗' },
          { hanzi: '层', pinyin: 'céng', ru: 'Этаж', em: '🏢' },
          { hanzi: '楼', pinyin: 'lóu', ru: 'Здание', em: '🏢' },
          { hanzi: '门', pinyin: 'mén', ru: 'Дверь', em: '🚪' },
          { hanzi: '窗户', pinyin: 'chuānghu', ru: 'Окно', em: '🪟' },
          { hanzi: '灯', pinyin: 'dēng', ru: 'Лампа', em: '💡' },
          { hanzi: '桌子', pinyin: 'zhuōzi', ru: 'Стол', em: '🪑' },
          { hanzi: '椅子', pinyin: 'yǐzi', ru: 'Стул', em: '💺' },
          { hanzi: '黑板', pinyin: 'hēibǎn', ru: 'Доска', em: '⬛' }
        ]
      },
      {
        id: 3,
        emoji: '🍽️',
        title: 'Еда и посуда',
        cls: 'dc3',
        words: [
          { hanzi: '蛋糕', pinyin: 'dàngāo', ru: 'Торт', em: '🎂' },
          { hanzi: '面包', pinyin: 'miànbāo', ru: 'Хлеб', em: '🍞' },
          { hanzi: '啤酒', pinyin: 'píjiǔ', ru: 'Пиво', em: '🍺' },
          { hanzi: '筷子', pinyin: 'kuàizi', ru: 'Палочки', em: '🥢' },
          { hanzi: '盘子', pinyin: 'pánzi', ru: 'Тарелка', em: '🍽️' },
          { hanzi: '碗', pinyin: 'wǎn', ru: 'Миска', em: '🥣' },
          { hanzi: '杯子', pinyin: 'bēizi', ru: 'Стакан', em: '🥤' },
          { hanzi: '瓶子', pinyin: 'píngzi', ru: 'Бутылка', em: '🍾' },
          { hanzi: '菜单', pinyin: 'càidān', ru: 'Меню', em: '📋' },
          { hanzi: '饱', pinyin: 'bǎo', ru: 'Сытый', em: '😋' },
          { hanzi: '饿', pinyin: 'è', ru: 'Голодный', em: '🍽️' },
          { hanzi: '渴', pinyin: 'kě', ru: 'Хотеть пить', em: '🥤' },
          { hanzi: '甜', pinyin: 'tián', ru: 'Сладкий', em: '🍬' }
        ]
      },
      {
        id: 4,
        emoji: '👔',
        title: 'Одежда и внешность',
        cls: 'dc4',
        words: [
          { hanzi: '衬衫', pinyin: 'chènshān', ru: 'Рубашка', em: '👔' },
          { hanzi: '裤子', pinyin: 'kùzi', ru: 'Штаны', em: '👖' },
          { hanzi: '裙子', pinyin: 'qúnzi', ru: 'Юбка', em: '👗' },
          { hanzi: '皮鞋', pinyin: 'píxié', ru: 'Туфли', em: '👞' },
          { hanzi: '帽子', pinyin: 'màozi', ru: 'Шляпа', em: '🎩' },
          { hanzi: '个子', pinyin: 'gèzi', ru: 'Рост', em: '📏' },
          { hanzi: '胖', pinyin: 'pàng', ru: 'Толстый', em: '🐷' },
          { hanzi: '瘦', pinyin: 'shòu', ru: 'Худой', em: '🧍' },
          { hanzi: '年轻', pinyin: 'niánqīng', ru: 'Молодой', em: '🧒' },
          { hanzi: '老', pinyin: 'lǎo', ru: 'Старый', em: '👴' }
        ]
      },
      {
        id: 5,
        emoji: '🧠',
        title: 'Тело и здоровье',
        cls: 'dc5',
        words: [
          { hanzi: '鼻子', pinyin: 'bízi', ru: 'Нос', em: '👃' },
          { hanzi: '耳朵', pinyin: 'ěrduo', ru: 'Ухо', em: '👂' },
          { hanzi: '口', pinyin: 'kǒu', ru: 'Рот', em: '👄' },
          { hanzi: '脸', pinyin: 'liǎn', ru: 'Лицо', em: '😊' },
          { hanzi: '脚', pinyin: 'jiǎo', ru: 'Нога', em: '🦶' },
          { hanzi: '腿', pinyin: 'tuǐ', ru: 'Нога (бедро)', em: '🦵' },
          { hanzi: '头发', pinyin: 'tóufa', ru: 'Волосы', em: '💇' },
          { hanzi: '感冒', pinyin: 'gǎnmào', ru: 'Простуда', em: '🤧' },
          { hanzi: '发烧', pinyin: 'fāshāo', ru: 'Лихорадка', em: '🌡️' },
          { hanzi: '疼', pinyin: 'téng', ru: 'Больно', em: '😣' },
          { hanzi: '健康', pinyin: 'jiànkāng', ru: 'Здоровый', em: '💪' },
          { hanzi: '刷牙', pinyin: 'shuāyá', ru: 'Чистить зубы', em: '🪥' },
          { hanzi: '洗澡', pinyin: 'xǐzǎo', ru: 'Принимать душ', em: '🚿' },
          { hanzi: '洗手间', pinyin: 'xǐshǒujiān', ru: 'Туалет', em: '🚻' }
        ]
      },
      {
        id: 6,
        emoji: '💼',
        title: 'Работа и учёба',
        cls: 'dc6',
        words: [
          { hanzi: '办公室', pinyin: 'bàngōngshì', ru: 'Офис', em: '🏢' },
          { hanzi: '办法', pinyin: 'bànfǎ', ru: 'Способ', em: '💡' },
          { hanzi: '帮忙', pinyin: 'bāngmáng', ru: 'Помогать', em: '🤝' },
          { hanzi: '笔记本', pinyin: 'bǐjìběn', ru: 'Тетрадь', em: '📓' },
          { hanzi: '必须', pinyin: 'bìxū', ru: 'Должен', em: '❗' },
          { hanzi: '考试', pinyin: 'kǎoshì', ru: 'Экзамен', em: '📝' },
          { hanzi: '练习', pinyin: 'liànxí', ru: 'Упражняться', em: '📝' },
          { hanzi: '留学', pinyin: 'liúxué', ru: 'Учиться за границей', em: '🌏' },
          { hanzi: '年级', pinyin: 'niánjí', ru: 'Класс (в школе)', em: '📚' },
          { hanzi: '认真', pinyin: 'rènzhēn', ru: 'Серьёзный', em: '🤓' },
          { hanzi: '数学', pinyin: 'shùxué', ru: 'Математика', em: '📐' },
          { hanzi: '水平', pinyin: 'shuǐpíng', ru: 'Уровень', em: '📊' },
          { hanzi: '体育', pinyin: 'tǐyù', ru: 'Физкультура', em: '🏃' },
          { hanzi: '图书馆', pinyin: 'túshūguǎn', ru: 'Библиотека', em: '📚' },
          { hanzi: '完成', pinyin: 'wánchéng', ru: 'Завершать', em: '✅' },
          { hanzi: '忘记', pinyin: 'wàngjì', ru: 'Забывать', em: '😅' },
          { hanzi: '文化', pinyin: 'wénhuà', ru: 'Культура', em: '🎭' },
          { hanzi: '新闻', pinyin: 'xīnwén', ru: 'Новости', em: '📰' },
          { hanzi: '信用卡', pinyin: 'xìnyòngkǎ', ru: 'Кредитная карта', em: '💳' },
          { hanzi: '行李', pinyin: 'xíngli', ru: 'Багаж', em: '🧳' },
          { hanzi: '选择', pinyin: 'xuǎnzé', ru: 'Выбирать', em: '🎯' },
          { hanzi: '要求', pinyin: 'yāoqiú', ru: 'Требовать', em: '📋' },
          { hanzi: '银行', pinyin: 'yínháng', ru: 'Банк', em: '🏦' },
          { hanzi: '应该', pinyin: 'yīnggāi', ru: 'Должен', em: '❗' },
          { hanzi: '影响', pinyin: 'yǐngxiǎng', ru: 'Влиять', em: '💫' },
          { hanzi: '游戏', pinyin: 'yóuxì', ru: 'Игра', em: '🎮' },
          { hanzi: '注意', pinyin: 'zhùyì', ru: 'Обращать внимание', em: '⚠️' },
          { hanzi: '作业', pinyin: 'zuòyè', ru: 'Домашнее задание', em: '📝' }
        ]
      },
      {
        id: 7,
        emoji: '🚗',
        title: 'Транспорт и путешествия',
        cls: 'dc7',
        words: [
          { hanzi: '船', pinyin: 'chuán', ru: 'Корабль', em: '🚢' },
          { hanzi: '地铁', pinyin: 'dìtiě', ru: 'Метро', em: '🚇' },
          { hanzi: '地图', pinyin: 'dìtú', ru: 'Карта', em: '🗺️' },
          { hanzi: '护照', pinyin: 'hùzhào', ru: 'Паспорт', em: '🛂' },
          { hanzi: '骑', pinyin: 'qí', ru: 'Ехать верхом', em: '🚴' },
          { hanzi: '起飞', pinyin: 'qǐfēi', ru: 'Взлетать', em: '✈️' },
          { hanzi: '司机', pinyin: 'sījī', ru: 'Водитель', em: '🚗' },
          { hanzi: '自行车', pinyin: 'zìxíngchē', ru: 'Велосипед', em: '🚲' },
          { hanzi: '站', pinyin: 'zhàn', ru: 'Станция', em: '🚉' }
        ]
      },
      {
        id: 8,
        emoji: '🌍',
        title: 'География и природа',
        cls: 'dc8',
        words: [
          { hanzi: '北方', pinyin: 'běifāng', ru: 'Север', em: '⬆️' },
          { hanzi: '东', pinyin: 'dōng', ru: 'Восток', em: '🌅' },
          { hanzi: '南', pinyin: 'nán', ru: 'Юг', em: '⬇️' },
          { hanzi: '西', pinyin: 'xī', ru: 'Запад', em: '⬅️' },
          { hanzi: '地方', pinyin: 'dìfang', ru: 'Место', em: '📍' },
          { hanzi: '国家', pinyin: 'guójiā', ru: 'Страна', em: '🏳️' },
          { hanzi: '黄河', pinyin: 'huánghé', ru: 'Жёлтая река', em: '🌊' },
          { hanzi: '世界', pinyin: 'shìjiè', ru: 'Мир', em: '🌍' },
          { hanzi: '树', pinyin: 'shù', ru: 'Дерево', em: '🌳' },
          { hanzi: '太阳', pinyin: 'tàiyáng', ru: 'Солнце', em: '☀️' },
          { hanzi: '月亮', pinyin: 'yuèliàng', ru: 'Луна', em: '🌙' },
          { hanzi: '鸟', pinyin: 'niǎo', ru: 'Птица', em: '🐦' },
          { hanzi: '马', pinyin: 'mǎ', ru: 'Лошадь', em: '🐴' },
          { hanzi: '草', pinyin: 'cǎo', ru: 'Трава', em: '🌿' },
          { hanzi: '花', pinyin: 'huā', ru: 'Цветок', em: '🌸' },
          { hanzi: '春', pinyin: 'chūn', ru: 'Весна', em: '🌸' },
          { hanzi: '秋', pinyin: 'qiū', ru: 'Осень', em: '🍂' },
          { hanzi: '冬', pinyin: 'dōng', ru: 'Зима', em: '❄️' },
          { hanzi: '季节', pinyin: 'jìjié', ru: 'Сезон', em: '🍂' }
        ]
      },
      {
        id: 9,
        emoji: '📱',
        title: 'Технологии и коммуникация',
        cls: 'dc9',
        words: [
          { hanzi: '上网', pinyin: 'shàngwǎng', ru: 'В интернете', em: '🌐' },
          { hanzi: '手机', pinyin: 'shǒujī', ru: 'Телефон', em: '📱' },
          { hanzi: '电脑', pinyin: 'diànnǎo', ru: 'Компьютер', em: '💻' },
          { hanzi: '电视', pinyin: 'diànshì', ru: 'Телевизор', em: '📺' },
          { hanzi: '音乐', pinyin: 'yīnyuè', ru: 'Музыка', em: '🎵' },
          { hanzi: '电影', pinyin: 'diànyǐng', ru: 'Фильм', em: '🎬' },
          { hanzi: '照片', pinyin: 'zhàopiàn', ru: 'Фото', em: '📸' },
          { hanzi: '照相机', pinyin: 'zhàoxiàngjī', ru: 'Фотоаппарат', em: '📷' }
        ]
      },
      {
        id: 10,
        emoji: '💬',
        title: 'Общение и речь',
        cls: 'dc10',
        words: [
          { hanzi: '啊', pinyin: 'a', ru: 'Ах', em: '😮' },
          { hanzi: '回答', pinyin: 'huídá', ru: 'Отвечать', em: '💬' },
          { hanzi: '讲', pinyin: 'jiǎng', ru: 'Рассказывать', em: '🗣️' },
          { hanzi: '教', pinyin: 'jiāo', ru: 'Учить', em: '📖' },
          { hanzi: '句子', pinyin: 'jùzi', ru: 'Предложение', em: '📝' },
          { hanzi: '聊天', pinyin: 'liáotiān', ru: 'Болтать', em: '💬' },
          { hanzi: '声音', pinyin: 'shēngyīn', ru: 'Голос', em: '🔊' },
          { hanzi: '试', pinyin: 'shì', ru: 'Пытаться', em: '💪' },
          { hanzi: '词典', pinyin: 'cídiǎn', ru: 'Словарь', em: '📕' },
          { hanzi: '中文', pinyin: 'zhōngwén', ru: 'Китайский язык', em: '🀄' }
        ]
      },
      {
        id: 11,
        emoji: '💖',
        title: 'Чувства и эмоции',
        cls: 'dc11',
        words: [
          { hanzi: '爱好', pinyin: 'àihào', ru: 'Хобби', em: '🎯' },
          { hanzi: '安静', pinyin: 'ānjìng', ru: 'Тихий', em: '🤫' },
          { hanzi: '担心', pinyin: 'dānxīn', ru: 'Беспокоиться', em: '😰' },
          { hanzi: '当然', pinyin: 'dāngrán', ru: 'Конечно', em: '👍' },
          { hanzi: '多么', pinyin: 'duōme', ru: 'Как (восклицание)', em: '❓' },
          { hanzi: '放心', pinyin: 'fàngxīn', ru: 'Быть спокойным', em: '😌' },
          { hanzi: '感兴趣', pinyin: 'gǎnxìngqù', ru: 'Интересоваться', em: '🤔' },
          { hanzi: '关系', pinyin: 'guānxi', ru: 'Отношения', em: '🤝' },
          { hanzi: '关心', pinyin: 'guānxīn', ru: 'Заботиться', em: '❤️' },
          { hanzi: '欢迎', pinyin: 'huānyíng', ru: 'Добро пожаловать', em: '👋' },
          { hanzi: '记得', pinyin: 'jìde', ru: 'Помнить', em: '🧠' },
          { hanzi: '见面', pinyin: 'jiànmiàn', ru: 'Встречаться', em: '🤝' },
          { hanzi: '可爱', pinyin: 'kě\'ài', ru: 'Милый', em: '🥰' },
          { hanzi: '哭', pinyin: 'kū', ru: 'Плакать', em: '😭' },
          { hanzi: '了解', pinyin: 'liǎojiě', ru: 'Понимать', em: '🧠' },
          { hanzi: '满意', pinyin: 'mǎnyì', ru: 'Довольный', em: '😊' },
          { hanzi: '难过', pinyin: 'nánguò', ru: 'Грустный', em: '😢' },
          { hanzi: '努力', pinyin: 'nǔlì', ru: 'Стараться', em: '💪' },
          { hanzi: '奇怪', pinyin: 'qíguài', ru: 'Странный', em: '🤔' },
          { hanzi: '清楚', pinyin: 'qīngchǔ', ru: 'Ясный', em: '💡' },
          { hanzi: '热情', pinyin: 'rèqíng', ru: 'Тёплый', em: '🔥' },
          { hanzi: '认为', pinyin: 'rènwéi', ru: 'Считать', em: '💭' },
          { hanzi: '容易', pinyin: 'róngyì', ru: 'Лёгкий', em: '👍' },
          { hanzi: '生气', pinyin: 'shēngqì', ru: 'Злиться', em: '😡' },
          { hanzi: '舒服', pinyin: 'shūfu', ru: 'Комфортный', em: '😌' },
          { hanzi: '特别', pinyin: 'tèbié', ru: 'Особенный', em: '⭐' },
          { hanzi: '提高', pinyin: 'tígāo', ru: 'Повышать', em: '📈' },
          { hanzi: '突然', pinyin: 'tūrán', ru: 'Вдруг', em: '😮' },
          { hanzi: '相信', pinyin: 'xiāngxìn', ru: 'Верить', em: '🤝' },
          { hanzi: '像', pinyin: 'xiàng', ru: 'Похожий', em: '🔄' },
          { hanzi: '需要', pinyin: 'xūyào', ru: 'Нуждаться', em: '💭' },
          { hanzi: '一直', pinyin: 'yīzhí', ru: 'Всё время', em: '🔄' },
          { hanzi: '一定', pinyin: 'yīdìng', ru: 'Обязательно', em: '❗' },
          { hanzi: '一共', pinyin: 'yīgòng', ru: 'Всего', em: '📊' },
          { hanzi: '一样', pinyin: 'yīyàng', ru: 'Одинаковый', em: '🔄' },
          { hanzi: '以前', pinyin: 'yǐqián', ru: 'Раньше', em: '⏪' },
          { hanzi: '一般', pinyin: 'yībān', ru: 'Обычный', em: '👍' },
          { hanzi: '用', pinyin: 'yòng', ru: 'Использовать', em: '🔧' },
          { hanzi: '有名', pinyin: 'yǒumíng', ru: 'Известный', em: '⭐' },
          { hanzi: '又', pinyin: 'yòu', ru: 'Опять', em: '🔄' },
          { hanzi: '遇到', pinyin: 'yùdào', ru: 'Встречать', em: '🤝' },
          { hanzi: '愿意', pinyin: 'yuànyì', ru: 'Желать', em: '💭' },
          { hanzi: '越', pinyin: 'yuè', ru: 'Всё более', em: '📈' },
          { hanzi: '最后', pinyin: 'zuìhòu', ru: 'Последний', em: '🏁' },
          { hanzi: '最近', pinyin: 'zuìjìn', ru: 'Недавно', em: '📅' },
          { hanzi: '终于', pinyin: 'zhōngyú', ru: 'Наконец', em: '🎉' },
          { hanzi: '重要', pinyin: 'zhòngyào', ru: 'Важный', em: '⭐' },
          { hanzi: '周末', pinyin: 'zhōumò', ru: 'Выходные', em: '🎉' },
          { hanzi: '主要', pinyin: 'zhǔyào', ru: 'Главный', em: '⭐' },
          { hanzi: '自己', pinyin: 'zìjǐ', ru: 'Сам', em: '🙋' },
          { hanzi: '总是', pinyin: 'zǒngshì', ru: 'Всегда', em: '🔄' }
        ]
      },
      {
        id: 12,
        emoji: '🏃',
        title: 'Глаголы действия',
        cls: 'dc12',
        words: [
          { hanzi: '搬', pinyin: 'bān', ru: 'Переезжать', em: '🚚' },
          { hanzi: '包', pinyin: 'bāo', ru: 'Сумка', em: '👜' },
          { hanzi: '被', pinyin: 'bèi', ru: 'Пассив', em: '📘' },
          { hanzi: '变化', pinyin: 'biànhuà', ru: 'Изменение', em: '🔄' },
          { hanzi: '参加', pinyin: 'cānjiā', ru: 'Участвовать', em: '🤝' },
          { hanzi: '差', pinyin: 'chà', ru: 'Плохой', em: '👎' },
          { hanzi: '成绩', pinyin: 'chéngjì', ru: 'Результат', em: '📊' },
          { hanzi: '迟到', pinyin: 'chídào', ru: 'Опоздать', em: '⏰' },
          { hanzi: '除了', pinyin: 'chúle', ru: 'Кроме', em: '🔀' },
          { hanzi: '聪明', pinyin: 'cōngming', ru: 'Умный', em: '🧠' },
          { hanzi: '打扫', pinyin: 'dǎsǎo', ru: 'Убирать', em: '🧹' },
          { hanzi: '打算', pinyin: 'dǎsuàn', ru: 'Планировать', em: '📝' },
          { hanzi: '带', pinyin: 'dài', ru: 'Брать', em: '👜' },
          { hanzi: '地', pinyin: 'de', ru: 'Частица (наречие)', em: '🔗' },
          { hanzi: '短', pinyin: 'duǎn', ru: 'Короткий', em: '📏' },
          { hanzi: '段', pinyin: 'duàn', ru: 'Отрезок', em: '📏' },
          { hanzi: '锻炼', pinyin: 'duànliàn', ru: 'Тренироваться', em: '🏋️' },
          { hanzi: '发', pinyin: 'fā', ru: 'Отправлять', em: '📤' },
          { hanzi: '发现', pinyin: 'fāxiàn', ru: 'Обнаружить', em: '🔍' },
          { hanzi: '方便', pinyin: 'fāngbiàn', ru: 'Удобный', em: '👍' },
          { hanzi: '放', pinyin: 'fàng', ru: 'Класть', em: '📥' },
          { hanzi: '分', pinyin: 'fēn', ru: 'Делить', em: '➗' },
          { hanzi: '复习', pinyin: 'fùxí', ru: 'Повторять', em: '📚' },
          { hanzi: '附近', pinyin: 'fùjìn', ru: 'Рядом', em: '📍' },
          { hanzi: '干净', pinyin: 'gānjìng', ru: 'Чистый', em: '✨' },
          { hanzi: '刚才', pinyin: 'gāngcái', ru: 'Только что', em: '⏰' },
          { hanzi: '根据', pinyin: 'gēnjù', ru: 'Согласно', em: '📋' },
          { hanzi: '跟', pinyin: 'gēn', ru: 'С (кем-то)', em: '👣' },
          { hanzi: '更', pinyin: 'gèng', ru: 'Более', em: '📈' },
          { hanzi: '公斤', pinyin: 'gōngjīn', ru: 'Килограмм', em: '⚖️' },
          { hanzi: '公园', pinyin: 'gōngyuán', ru: 'Парк', em: '🌳' },
          { hanzi: '故事', pinyin: 'gùshi', ru: 'История', em: '📖' },
          { hanzi: '刮风', pinyin: 'guāfēng', ru: 'Ветер (дует)', em: '💨' },
          { hanzi: '关', pinyin: 'guān', ru: 'Закрывать', em: '🔒' },
          { hanzi: '关于', pinyin: 'guānyú', ru: 'О', em: 'ℹ️' },
          { hanzi: '过', pinyin: 'guò', ru: 'Проходить', em: '➡️' },
          { hanzi: '过去', pinyin: 'guòqù', ru: 'Прошлое', em: '⏪' },
          { hanzi: '还是', pinyin: 'háishi', ru: 'Или', em: '🤔' },
          { hanzi: '害怕', pinyin: 'hàipà', ru: 'Бояться', em: '😨' },
          { hanzi: '后来', pinyin: 'hòulái', ru: 'Позже', em: '⏩' },
          { hanzi: '画', pinyin: 'huà', ru: 'Рисовать', em: '🎨' },
          { hanzi: '坏', pinyin: 'huài', ru: 'Плохой', em: '👎' },
          { hanzi: '换', pinyin: 'huàn', ru: 'Менять', em: '🔄' },
          { hanzi: '会议', pinyin: 'huìyì', ru: 'Собрание', em: '📋' },
          { hanzi: '或者', pinyin: 'huòzhě', ru: 'Или', em: '🤔' },
          { hanzi: '几乎', pinyin: 'jīhū', ru: 'Почти', em: '🔢' },
          { hanzi: '机会', pinyin: 'jīhuì', ru: 'Возможность', em: '🎯' },
          { hanzi: '极', pinyin: 'jí', ru: 'Чрезвычайно', em: '💪' },
          { hanzi: '检查', pinyin: 'jiǎnchá', ru: 'Проверять', em: '🔍' },
          { hanzi: '简单', pinyin: 'jiǎndān', ru: 'Простой', em: '👍' },
          { hanzi: '角', pinyin: 'jiǎo', ru: 'Угол', em: '📐' },
          { hanzi: '接', pinyin: 'jiē', ru: 'Принимать', em: '🤲' },
          { hanzi: '街道', pinyin: 'jiēdào', ru: 'Улица', em: '🏙️' },
          { hanzi: '节目', pinyin: 'jiémù', ru: 'Программа', em: '📺' },
          { hanzi: '结束', pinyin: 'jiéshù', ru: 'Заканчивать', em: '✅' },
          { hanzi: '节日', pinyin: 'jiérì', ru: 'Праздник', em: '🎉' },
          { hanzi: '解决', pinyin: 'jiějué', ru: 'Решать', em: '💡' },
          { hanzi: '借', pinyin: 'jiè', ru: 'Одалживать', em: '🔄' },
          { hanzi: '经常', pinyin: 'jīngcháng', ru: 'Часто', em: '🔄' },
          { hanzi: '经过', pinyin: 'jīngguò', ru: 'Через', em: '➡️' },
          { hanzi: '久', pinyin: 'jiǔ', ru: 'Долго', em: '⏳' },
          { hanzi: '决定', pinyin: 'juédìng', ru: 'Решать', em: '📌' },
          { hanzi: '刻', pinyin: 'kè', ru: 'Вырезать', em: '🔪' },
          { hanzi: '离开', pinyin: 'líkāi', ru: 'Уезжать', em: '🚶' },
          { hanzi: '礼物', pinyin: 'lǐwù', ru: 'Подарок', em: '🎁' },
          { hanzi: '历史', pinyin: 'lìshǐ', ru: 'История', em: '📜' },
          { hanzi: '辆', pinyin: 'liàng', ru: 'Счётное (транспорт)', em: '🚗' },
          { hanzi: '绿', pinyin: 'lǜ', ru: 'Зелёный', em: '🟢' },
          { hanzi: '马上', pinyin: 'mǎshàng', ru: 'Сейчас (немедленно)', em: '⏰' },
          { hanzi: '米', pinyin: 'mǐ', ru: 'Метр', em: '📏' },
          { hanzi: '明白', pinyin: 'míngbai', ru: 'Понимать', em: '💡' },
          { hanzi: '拿', pinyin: 'ná', ru: 'Брать', em: '✋' },
          { hanzi: '难', pinyin: 'nán', ru: 'Трудный', em: '🤯' },
          { hanzi: '爬山', pinyin: 'páshān', ru: 'Восходить', em: '⛰️' },
          { hanzi: '其实', pinyin: 'qíshí', ru: 'На самом деле', em: '💡' },
          { hanzi: '其他', pinyin: 'qítā', ru: 'Другие', em: '🔀' },
          { hanzi: '起来', pinyin: 'qǐlái', ru: 'Вставать', em: '🛏️' },
          { hanzi: '请假', pinyin: 'qǐngjià', ru: 'Брать отгул', em: '📝' },
          { hanzi: '然后', pinyin: 'ránhòu', ru: 'Затем', em: '➡️' },
          { hanzi: '如果', pinyin: 'rúguǒ', ru: 'Если', em: '🤔' },
          { hanzi: '伞', pinyin: 'sǎn', ru: 'Зонт', em: '☂️' },
          { hanzi: '双', pinyin: 'shuāng', ru: 'Пара', em: '2️⃣' },
          { hanzi: '条', pinyin: 'tiáo', ru: 'Счётное (длинное)', em: '📏' },
          { hanzi: '同意', pinyin: 'tóngyì', ru: 'Соглашаться', em: '👍' },
          { hanzi: '为', pinyin: 'wèi', ru: 'Для', em: '🎯' },
          { hanzi: '为了', pinyin: 'wèile', ru: 'Ради', em: '🎯' },
          { hanzi: '位', pinyin: 'wèi', ru: 'Счётное (люди)', em: '👤' },
          { hanzi: '习惯', pinyin: 'xíguàn', ru: 'Привычка', em: '🔄' },
          { hanzi: '先', pinyin: 'xiān', ru: 'Сначала', em: '1️⃣' },
          { hanzi: '香蕉', pinyin: 'xiāngjiāo', ru: 'Банан', em: '🍌' },
          { hanzi: '向', pinyin: 'xiàng', ru: 'В сторону', em: '➡️' },
          { hanzi: '小时', pinyin: 'xiǎoshí', ru: 'Час', em: '🕐' },
          { hanzi: '新鲜', pinyin: 'xīnxiān', ru: 'Свежий', em: '🌿' },
          { hanzi: '行李箱', pinyin: 'xínglixiāng', ru: 'Чемодан', em: '🧳' },
          { hanzi: '熊猫', pinyin: 'xióngmāo', ru: 'Панда', em: '🐼' },
          { hanzi: '一边', pinyin: 'yībiān', ru: 'Одна сторона', em: '👈' },
          { hanzi: '一会儿', pinyin: 'yīhuìr', ru: 'Немного (время)', em: '⏳' },
          { hanzi: '饮料', pinyin: 'yǐnliào', ru: 'Напиток', em: '🥤' },
          { hanzi: '元', pinyin: 'yuán', ru: 'Юань', em: '💰' },
          { hanzi: '张', pinyin: 'zhāng', ru: 'Счётное (плоское)', em: '📄' },
          { hanzi: '长', pinyin: 'zhǎng', ru: 'Расти', em: '🌱' },
          { hanzi: '照相机', pinyin: 'zhàoxiàngjī', ru: 'Фотоаппарат', em: '📷' },
          { hanzi: '只', pinyin: 'zhǐ', ru: 'Только', em: '🔢' },
          { hanzi: '只有', pinyin: 'zhǐyǒu', ru: 'Только если', em: '🔒' },
          { hanzi: '中间', pinyin: 'zhōngjiān', ru: 'Середина', em: '📍' },
          { hanzi: '种', pinyin: 'zhǒng', ru: 'Вид (тип)', em: '🔢' },
          { hanzi: '嘴', pinyin: 'zuǐ', ru: 'Рот', em: '👄' },
          { hanzi: '左右', pinyin: 'zuǒyòu', ru: 'Около', em: '🔢' }
        ]
      }
    ]
  },

  // ========== HSK 4 (ПОЛНАЯ ВЕРСИЯ ~600 СЛОВ) ==========
  hsk4: {
    label: 'HSK 4',
    decks: [
      // ============================================================
      // ЧАСТЬ 1: A-B (1-50)
      // ============================================================
      {
        id: 1,
        emoji: '💕',
        title: 'A: Чувства и отношения',
        cls: 'dc1',
        words: [
          { hanzi: '爱情', pinyin: 'ài qíng', ru: 'Любовь', em: '❤️' },
          { hanzi: '安排', pinyin: 'ān pái', ru: 'Планировать', em: '📋' },
          { hanzi: '安全', pinyin: 'ān quán', ru: 'Безопасный', em: '🛡️' },
          { hanzi: '按时', pinyin: 'àn shí', ru: 'Вовремя', em: '⏰' },
          { hanzi: '按照', pinyin: 'àn zhào', ru: 'Согласно', em: '📋' },
          { hanzi: '阿姨', pinyin: 'ā yí', ru: 'Тётя', em: '👩' },
          { hanzi: '矮', pinyin: 'ǎi', ru: 'Низкий', em: '📏' }
        ]
      },
      {
        id: 2,
        emoji: '📚',
        title: 'B: Учёба и работа',
        cls: 'dc2',
        words: [
          { hanzi: '百分之', pinyin: 'bǎi fēn zhī', ru: 'Процент', em: '%' },
          { hanzi: '棒', pinyin: 'bàng', ru: 'Отличный', em: '👍' },
          { hanzi: '包子', pinyin: 'bāo zi', ru: 'Булочка', em: '🥟' },
          { hanzi: '保护', pinyin: 'bǎo hù', ru: 'Защищать', em: '🛡️' },
          { hanzi: '保证', pinyin: 'bǎo zhèng', ru: 'Гарантировать', em: '🤝' },
          { hanzi: '报名', pinyin: 'bào míng', ru: 'Записываться', em: '📝' },
          { hanzi: '抱', pinyin: 'bào', ru: 'Обнимать', em: '🤗' },
          { hanzi: '抱歉', pinyin: 'bào qiàn', ru: 'Извиняться', em: '😔' },
          { hanzi: '倍', pinyin: 'bèi', ru: 'Раз (в разы)', em: '✖️' },
          { hanzi: '本来', pinyin: 'běn lái', ru: 'Первоначально', em: '🔙' },
          { hanzi: '笨', pinyin: 'bèn', ru: 'Глупый', em: '🐻' },
          { hanzi: '比如', pinyin: 'bǐ rú', ru: 'Например', em: '📝' },
          { hanzi: '毕业', pinyin: 'bì yè', ru: 'Заканчивать', em: '🎓' },
          { hanzi: '遍', pinyin: 'biàn', ru: 'Раз (действие)', em: '🔄' },
          { hanzi: '标准', pinyin: 'biāo zhǔn', ru: 'Стандарт', em: '📏' },
          { hanzi: '表格', pinyin: 'biǎo gé', ru: 'Таблица', em: '📊' },
          { hanzi: '表示', pinyin: 'biǎo shì', ru: 'Выражать', em: '💬' },
          { hanzi: '表演', pinyin: 'biǎo yǎn', ru: 'Выступать', em: '🎭' },
          { hanzi: '表扬', pinyin: 'biǎo yáng', ru: 'Хвалить', em: '👏' },
          { hanzi: '饼干', pinyin: 'bǐng gān', ru: 'Печенье', em: '🍪' },
          { hanzi: '并且', pinyin: 'bìng qiě', ru: 'Кроме того', em: '➕' },
          { hanzi: '博士', pinyin: 'bó shì', ru: 'Доктор наук', em: '🎓' },
          { hanzi: '不过', pinyin: 'bù guò', ru: 'Однако', em: '🤔' },
          { hanzi: '不得不', pinyin: 'bù dé bù', ru: 'Вынужден', em: '😤' },
          { hanzi: '不管', pinyin: 'bù guǎn', ru: 'Независимо от', em: '🤷' },
          { hanzi: '不仅', pinyin: 'bù jǐn', ru: 'Не только', em: '➕' },
          { hanzi: '部分', pinyin: 'bù fen', ru: 'Часть', em: '🧩' }
        ]
      },

      // ============================================================
      // ЧАСТЬ 2: C-D (51-120)
      // ============================================================
      {
        id: 3,
        emoji: '🔍',
        title: 'C: Действия и поиск',
        cls: 'dc3',
        words: [
          { hanzi: '擦', pinyin: 'cā', ru: 'Вытирать', em: '🧹' },
          { hanzi: '猜', pinyin: 'cāi', ru: 'Угадывать', em: '🤔' },
          { hanzi: '材料', pinyin: 'cái liào', ru: 'Материал', em: '📦' },
          { hanzi: '参观', pinyin: 'cān guān', ru: 'Посещать', em: '🏛️' },
          { hanzi: '餐厅', pinyin: 'cān tīng', ru: 'Ресторан', em: '🍽️' },
          { hanzi: '厕所', pinyin: 'cè suǒ', ru: 'Туалет', em: '🚻' },
          { hanzi: '差不多', pinyin: 'chà bu duō', ru: 'Почти', em: '🔢' },
          { hanzi: '尝', pinyin: 'cháng', ru: 'Пробовать', em: '👅' },
          { hanzi: '长城', pinyin: 'cháng chéng', ru: 'Великая стена', em: '🏯' },
          { hanzi: '长江', pinyin: 'cháng jiāng', ru: 'Река Янцзы', em: '🌊' },
          { hanzi: '场', pinyin: 'chǎng', ru: 'Поле, место', em: '📍' },
          { hanzi: '超过', pinyin: 'chāo guò', ru: 'Превышать', em: '📈' },
          { hanzi: '乘坐', pinyin: 'chéng zuò', ru: 'Ехать на', em: '🚗' },
          { hanzi: '成功', pinyin: 'chéng gōng', ru: 'Успех', em: '🏆' },
          { hanzi: '成为', pinyin: 'chéng wéi', ru: 'Становиться', em: '🔄' },
          { hanzi: '诚实', pinyin: 'chéng shí', ru: 'Честный', em: '🤝' },
          { hanzi: '吃惊', pinyin: 'chī jīng', ru: 'Удивляться', em: '😮' },
          { hanzi: '重新', pinyin: 'chóng xīn', ru: 'Заново', em: '🔄' },
          { hanzi: '抽烟', pinyin: 'chōu yān', ru: 'Курить', em: '🚬' },
          { hanzi: '出差', pinyin: 'chū chāi', ru: 'Командировка', em: '💼' },
          { hanzi: '出发', pinyin: 'chū fā', ru: 'Отправляться', em: '🚀' },
          { hanzi: '出生', pinyin: 'chū shēng', ru: 'Родиться', em: '👶' },
          { hanzi: '出现', pinyin: 'chū xiàn', ru: 'Появляться', em: '👻' },
          { hanzi: '厨房', pinyin: 'chú fáng', ru: 'Кухня', em: '🍳' },
          { hanzi: '传真', pinyin: 'chuán zhēn', ru: 'Факс', em: '📠' },
          { hanzi: '窗户', pinyin: 'chuāng hu', ru: 'Окно', em: '🪟' },
          { hanzi: '词语', pinyin: 'cí yǔ', ru: 'Слова', em: '📝' },
          { hanzi: '从来', pinyin: 'cóng lái', ru: 'Всегда', em: '🔄' },
          { hanzi: '粗心', pinyin: 'cū xīn', ru: 'Небрежный', em: '😅' },
          { hanzi: '存', pinyin: 'cún', ru: 'Хранить', em: '💾' },
          { hanzi: '错误', pinyin: 'cuò wù', ru: 'Ошибка', em: '❌' }
        ]
      },
      {
        id: 4,
        emoji: '📝',
        title: 'D: Ответы и действия',
        cls: 'dc4',
        words: [
          { hanzi: '答案', pinyin: 'dá àn', ru: 'Ответ', em: '💡' },
          { hanzi: '打扮', pinyin: 'dǎ ban', ru: 'Наряжаться', em: '💄' },
          { hanzi: '打扰', pinyin: 'dǎ rǎo', ru: 'Беспокоить', em: '🚫' },
          { hanzi: '打印', pinyin: 'dǎ yìn', ru: 'Печатать', em: '🖨️' },
          { hanzi: '打招呼', pinyin: 'dǎ zhāo hu', ru: 'Приветствовать', em: '👋' },
          { hanzi: '打折', pinyin: 'dǎ zhé', ru: 'Скидка', em: '🏷️' },
          { hanzi: '打针', pinyin: 'dǎ zhēn', ru: 'Делать укол', em: '💉' },
          { hanzi: '大概', pinyin: 'dà gài', ru: 'Примерно', em: '🔢' },
          { hanzi: '大使馆', pinyin: 'dà shǐ guǎn', ru: 'Посольство', em: '🏛️' },
          { hanzi: '大约', pinyin: 'dà yuē', ru: 'Около', em: '🔢' },
          { hanzi: '大夫', pinyin: 'dài fu', ru: 'Врач', em: '🏥' },
          { hanzi: '戴', pinyin: 'dài', ru: 'Носить (на себе)', em: '👕' },
          { hanzi: '当', pinyin: 'dāng', ru: 'В качестве', em: '🔀' },
          { hanzi: '当时', pinyin: 'dāng shí', ru: 'Тогда', em: '⏰' },
          { hanzi: '刀', pinyin: 'dāo', ru: 'Нож', em: '🔪' },
          { hanzi: '导游', pinyin: 'dǎo yóu', ru: 'Гид', em: '🧭' },
          { hanzi: '倒', pinyin: 'dào', ru: 'Переворачивать', em: '🔄' },
          { hanzi: '到处', pinyin: 'dào chù', ru: 'Везде', em: '🌍' },
          { hanzi: '到底', pinyin: 'dào dǐ', ru: 'В конце концов', em: '🏁' },
          { hanzi: '道歉', pinyin: 'dào qiàn', ru: 'Извиняться', em: '🙏' },
          { hanzi: '得', pinyin: 'dé', ru: 'Получать', em: '🎁' },
          { hanzi: '得意', pinyin: 'dé yì', ru: 'Гордиться', em: '😏' },
          { hanzi: '登机牌', pinyin: 'dēng jī pái', ru: 'Посадочный талон', em: '🎫' },
          { hanzi: '等', pinyin: 'děng', ru: 'Ждать', em: '⏳' },
          { hanzi: '低', pinyin: 'dī', ru: 'Низкий', em: '⬇️' },
          { hanzi: '底', pinyin: 'dǐ', ru: 'Дно', em: '⬇️' },
          { hanzi: '地点', pinyin: 'dì diǎn', ru: 'Место', em: '📍' },
          { hanzi: '地球', pinyin: 'dì qiú', ru: 'Земля', em: '🌍' },
          { hanzi: '地址', pinyin: 'dì zhǐ', ru: 'Адрес', em: '📍' },
          { hanzi: '掉', pinyin: 'diào', ru: 'Падать', em: '📉' },
          { hanzi: '调查', pinyin: 'diào chá', ru: 'Исследовать', em: '🔍' },
          { hanzi: '丢', pinyin: 'diū', ru: 'Терять', em: '😅' },
          { hanzi: '动作', pinyin: 'dòng zuò', ru: 'Действие', em: '🏃' },
          { hanzi: '堵车', pinyin: 'dǔ chē', ru: 'Пробка', em: '🚗' },
          { hanzi: '肚子', pinyin: 'dù zi', ru: 'Живот', em: '🤰' },
          { hanzi: '短信', pinyin: 'duǎn xìn', ru: 'СМС', em: '📱' },
          { hanzi: '对话', pinyin: 'duì huà', ru: 'Диалог', em: '💬' },
          { hanzi: '对面', pinyin: 'duì miàn', ru: 'Напротив', em: '👀' },
          { hanzi: '对于', pinyin: 'duì yú', ru: 'Относительно', em: 'ℹ️' }
        ]
      },

      // ============================================================
      // ЧАСТЬ 3: E-G (121-180)
      // ============================================================
      {
        id: 5,
        emoji: '🌍',
        title: 'E-G: Мир и природа',
        cls: 'dc5',
        words: [
          { hanzi: '儿童', pinyin: 'ér tóng', ru: 'Ребёнок', em: '👶' },
          { hanzi: '而', pinyin: 'ér', ru: 'И (союз)', em: '🔗' },
          { hanzi: '发生', pinyin: 'fā shēng', ru: 'Случаться', em: '💥' },
          { hanzi: '发展', pinyin: 'fā zhǎn', ru: 'Развивать', em: '📈' },
          { hanzi: '法律', pinyin: 'fǎ lǜ', ru: 'Закон', em: '⚖️' },
          { hanzi: '翻译', pinyin: 'fān yì', ru: 'Переводить', em: '🌐' },
          { hanzi: '烦恼', pinyin: 'fán nǎo', ru: 'Беспокоиться', em: '😟' },
          { hanzi: '反对', pinyin: 'fǎn duì', ru: 'Против', em: '🚫' },
          { hanzi: '方法', pinyin: 'fāng fǎ', ru: 'Метод', em: '💡' },
          { hanzi: '方面', pinyin: 'fāng miàn', ru: 'Аспект', em: '📐' },
          { hanzi: '方向', pinyin: 'fāng xiàng', ru: 'Направление', em: '🧭' },
          { hanzi: '房东', pinyin: 'fáng dōng', ru: 'Арендодатель', em: '🏠' },
          { hanzi: '放弃', pinyin: 'fàng qì', ru: 'Бросать', em: '🚫' },
          { hanzi: '放暑假', pinyin: 'fàng shǔ jià', ru: 'Летние каникулы', em: '☀️' },
          { hanzi: '放松', pinyin: 'fàng sōng', ru: 'Расслабляться', em: '😌' },
          { hanzi: '份', pinyin: 'fèn', ru: 'Часть', em: '🧩' },
          { hanzi: '丰富', pinyin: 'fēng fù', ru: 'Богатый', em: '💰' },
          { hanzi: '否则', pinyin: 'fǒu zé', ru: 'Иначе', em: '⚠️' },
          { hanzi: '符合', pinyin: 'fú hé', ru: 'Соответствовать', em: '✅' },
          { hanzi: '付款', pinyin: 'fù kuǎn', ru: 'Платить', em: '💳' },
          { hanzi: '复印', pinyin: 'fù yìn', ru: 'Копировать', em: '📄' },
          { hanzi: '复杂', pinyin: 'fù zá', ru: 'Сложный', em: '🤯' },
          { hanzi: '富', pinyin: 'fù', ru: 'Богатый', em: '💰' },
          { hanzi: '父亲', pinyin: 'fù qin', ru: 'Отец', em: '👨' },
          { hanzi: '负责', pinyin: 'fù zé', ru: 'Отвечать', em: '💼' }
        ]
      },
      {
        id: 6,
        emoji: '🔄',
        title: 'G: Изменения и действия',
        cls: 'dc6',
        words: [
          { hanzi: '改变', pinyin: 'gǎi biàn', ru: 'Менять', em: '🔄' },
          { hanzi: '干杯', pinyin: 'gān bēi', ru: 'Тост', em: '🍻' },
          { hanzi: '感动', pinyin: 'gǎn dòng', ru: 'Трогать', em: '🥺' },
          { hanzi: '感觉', pinyin: 'gǎn jué', ru: 'Чувствовать', em: '🤔' },
          { hanzi: '感情', pinyin: 'gǎn qíng', ru: 'Чувство', em: '💖' },
          { hanzi: '感谢', pinyin: 'gǎn xiè', ru: 'Благодарить', em: '🙏' },
          { hanzi: '敢', pinyin: 'gǎn', ru: 'Сметь', em: '💪' },
          { hanzi: '赶', pinyin: 'gǎn', ru: 'Спешить', em: '🏃' },
          { hanzi: '干', pinyin: 'gàn', ru: 'Делать', em: '🔨' },
          { hanzi: '刚', pinyin: 'gāng', ru: 'Только что', em: '⏰' },
          { hanzi: '高速公路', pinyin: 'gāo sù gōng lù', ru: 'Шоссе', em: '🛣️' },
          { hanzi: '胳膊', pinyin: 'gē bo', ru: 'Рука (плечо)', em: '💪' },
          { hanzi: '各', pinyin: 'gè', ru: 'Каждый', em: '🔢' },
          { hanzi: '公里', pinyin: 'gōng lǐ', ru: 'Километр', em: '📏' },
          { hanzi: '功夫', pinyin: 'gōng fu', ru: 'Навык', em: '💪' },
          { hanzi: '工资', pinyin: 'gōng zī', ru: 'Зарплата', em: '💰' },
          { hanzi: '共同', pinyin: 'gòng tóng', ru: 'Совместный', em: '👥' },
          { hanzi: '够', pinyin: 'gòu', ru: 'Достаточно', em: '✅' },
          { hanzi: '购物', pinyin: 'gòu wù', ru: 'Покупать', em: '🛍️' },
          { hanzi: '估计', pinyin: 'gū jì', ru: 'Оценивать', em: '📊' },
          { hanzi: '鼓励', pinyin: 'gǔ lì', ru: 'Поощрять', em: '👏' },
          { hanzi: '故意', pinyin: 'gù yì', ru: 'Намеренно', em: '🎯' },
          { hanzi: '顾客', pinyin: 'gù kè', ru: 'Клиент', em: '👤' },
          { hanzi: '挂', pinyin: 'guà', ru: 'Вешать', em: '📌' },
          { hanzi: '关键', pinyin: 'guān jiàn', ru: 'Ключевой', em: '🔑' },
          { hanzi: '观众', pinyin: 'guān zhòng', ru: 'Зритель', em: '👀' },
          { hanzi: '管理', pinyin: 'guǎn lǐ', ru: 'Управлять', em: '📋' },
          { hanzi: '光', pinyin: 'guāng', ru: 'Свет', em: '💡' },
          { hanzi: '广播', pinyin: 'guǎng bō', ru: 'Радио', em: '📻' },
          { hanzi: '广告', pinyin: 'guǎng gào', ru: 'Реклама', em: '📢' },
          { hanzi: '逛', pinyin: 'guàng', ru: 'Гулять (по магазинам)', em: '🛍️' },
          { hanzi: '规定', pinyin: 'guī dìng', ru: 'Правило', em: '📋' },
          { hanzi: '国籍', pinyin: 'guó jí', ru: 'Гражданство', em: '🛂' },
          { hanzi: '国际', pinyin: 'guó jì', ru: 'Международный', em: '🌍' },
          { hanzi: '果汁', pinyin: 'guǒ zhī', ru: 'Сок', em: '🧃' },
          { hanzi: '过程', pinyin: 'guò chéng', ru: 'Процесс', em: '🔄' }
        ]
      },

      // ============================================================
      // ЧАСТЬ 4: H-L (181-280)
      // ============================================================
      {
        id: 7,
        emoji: '🌊',
        title: 'H: Природа и здоровье',
        cls: 'dc7',
        words: [
          { hanzi: '海洋', pinyin: 'hǎi yáng', ru: 'Океан', em: '🌊' },
          { hanzi: '害羞', pinyin: 'hài xiū', ru: 'Стесняться', em: '😳' },
          { hanzi: '寒假', pinyin: 'hán jià', ru: 'Зимние каникулы', em: '❄️' },
          { hanzi: '汗', pinyin: 'hàn', ru: 'Пот', em: '💦' },
          { hanzi: '航班', pinyin: 'háng bān', ru: 'Рейс', em: '✈️' },
          { hanzi: '好处', pinyin: 'hǎo chu', ru: 'Польза', em: '👍' },
          { hanzi: '好像', pinyin: 'hǎo xiàng', ru: 'Кажется', em: '🤔' },
          { hanzi: '号码', pinyin: 'hào mǎ', ru: 'Номер', em: '🔢' },
          { hanzi: '合格', pinyin: 'hé gé', ru: 'Квалифицированный', em: '✅' },
          { hanzi: '合适', pinyin: 'hé shì', ru: 'Подходящий', em: '👍' },
          { hanzi: '盒子', pinyin: 'hé zi', ru: 'Коробка', em: '📦' },
          { hanzi: '厚', pinyin: 'hòu', ru: 'Толстый', em: '📏' },
          { hanzi: '后悔', pinyin: 'hòu huǐ', ru: 'Сожалеть', em: '😞' },
          { hanzi: '互联网', pinyin: 'hù lián wǎng', ru: 'Интернет', em: '🌐' },
          { hanzi: '互相', pinyin: 'hù xiāng', ru: 'Взаимно', em: '🔄' },
          { hanzi: '护士', pinyin: 'hù shi', ru: 'Медсестра', em: '👩‍⚕️' },
          { hanzi: '怀疑', pinyin: 'huái yí', ru: 'Сомневаться', em: '🤨' },
          { hanzi: '回忆', pinyin: 'huí yì', ru: 'Вспоминать', em: '🧠' },
          { hanzi: '活动', pinyin: 'huó dòng', ru: 'Мероприятие', em: '🎉' },
          { hanzi: '活泼', pinyin: 'huó po', ru: 'Живой', em: '😄' },
          { hanzi: '火', pinyin: 'huǒ', ru: 'Огонь', em: '🔥' },
          { hanzi: '获得', pinyin: 'huò dé', ru: 'Получать', em: '🏆' }
        ]
      },
      {
        id: 8,
        emoji: '💪',
        title: 'J: Действия и эмоции',
        cls: 'dc8',
        words: [
          { hanzi: '基础', pinyin: 'jī chǔ', ru: 'Основа', em: '📚' },
          { hanzi: '激动', pinyin: 'jī dòng', ru: 'Волноваться', em: '😆' },
          { hanzi: '积极', pinyin: 'jī jí', ru: 'Активный', em: '💪' },
          { hanzi: '积累', pinyin: 'jī lěi', ru: 'Накапливать', em: '📈' },
          { hanzi: '即使', pinyin: 'jí shǐ', ru: 'Даже если', em: '🤔' },
          { hanzi: '及时', pinyin: 'jí shí', ru: 'Своевременный', em: '⏰' },
          { hanzi: '寄', pinyin: 'jì', ru: 'Отправлять', em: '📤' },
          { hanzi: '技术', pinyin: 'jì shù', ru: 'Технология', em: '🖥️' },
          { hanzi: '既然', pinyin: 'jì rán', ru: 'Поскольку', em: '🤔' },
          { hanzi: '继续', pinyin: 'jì xù', ru: 'Продолжать', em: '▶️' },
          { hanzi: '计划', pinyin: 'jì huà', ru: 'План', em: '📋' },
          { hanzi: '记者', pinyin: 'jì zhě', ru: 'Журналист', em: '📰' },
          { hanzi: '加班', pinyin: 'jiā bān', ru: 'Сверхурочная работа', em: '💼' },
          { hanzi: '加油站', pinyin: 'jiā yóu zhàn', ru: 'Заправка', em: '⛽' },
          { hanzi: '家具', pinyin: 'jiā jù', ru: 'Мебель', em: '🪑' },
          { hanzi: '价格', pinyin: 'jià gé', ru: 'Цена', em: '🏷️' },
          { hanzi: '坚持', pinyin: 'jiān chí', ru: 'Настаивать', em: '💪' },
          { hanzi: '减肥', pinyin: 'jiǎn féi', ru: 'Худеть', em: '🏋️' },
          { hanzi: '减少', pinyin: 'jiǎn shǎo', ru: 'Уменьшать', em: '📉' },
          { hanzi: '建议', pinyin: 'jiàn yì', ru: 'Предложение', em: '💡' },
          { hanzi: '将来', pinyin: 'jiāng lái', ru: 'Будущее', em: '🔮' },
          { hanzi: '奖金', pinyin: 'jiǎng jīn', ru: 'Премия', em: '💰' },
          { hanzi: '降低', pinyin: 'jiàng dī', ru: 'Снижать', em: '📉' },
          { hanzi: '降落', pinyin: 'jiàng luò', ru: 'Приземляться', em: '🛬' },
          { hanzi: '交', pinyin: 'jiāo', ru: 'Сдавать', em: '📤' },
          { hanzi: '交流', pinyin: 'jiāo liú', ru: 'Общаться', em: '💬' },
          { hanzi: '交通', pinyin: 'jiāo tōng', ru: 'Транспорт', em: '🚗' },
          { hanzi: '郊区', pinyin: 'jiāo qū', ru: 'Пригород', em: '🏡' },
          { hanzi: '骄傲', pinyin: 'jiāo ào', ru: 'Гордый', em: '🦚' },
          { hanzi: '饺子', pinyin: 'jiǎo zi', ru: 'Пельмени', em: '🥟' },
          { hanzi: '教授', pinyin: 'jiào shòu', ru: 'Профессор', em: '👨‍🏫' },
          { hanzi: '教育', pinyin: 'jiào yù', ru: 'Образование', em: '📚' },
          { hanzi: '接受', pinyin: 'jiē shòu', ru: 'Принимать', em: '🤲' },
          { hanzi: '接着', pinyin: 'jiē zhe', ru: 'Затем', em: '➡️' },
          { hanzi: '结果', pinyin: 'jié guǒ', ru: 'Результат', em: '📊' },
          { hanzi: '节', pinyin: 'jié', ru: 'Праздник', em: '🎉' },
          { hanzi: '节约', pinyin: 'jié yuē', ru: 'Экономить', em: '💰' },
          { hanzi: '解释', pinyin: 'jiě shì', ru: 'Объяснять', em: '💡' },
          { hanzi: '尽管', pinyin: 'jǐn guǎn', ru: 'Хотя', em: '🤔' },
          { hanzi: '紧张', pinyin: 'jǐn zhāng', ru: 'Нервный', em: '😰' },
          { hanzi: '禁止', pinyin: 'jìn zhǐ', ru: 'Запрещать', em: '🚫' },
          { hanzi: '进行', pinyin: 'jìn xíng', ru: 'Проводить', em: '▶️' },
          { hanzi: '京剧', pinyin: 'jīng jù', ru: 'Пекинская опера', em: '🎭' },
          { hanzi: '精彩', pinyin: 'jīng cǎi', ru: 'Замечательный', em: '🌟' },
          { hanzi: '经济', pinyin: 'jīng jì', ru: 'Экономика', em: '📈' },
          { hanzi: '经历', pinyin: 'jīng lì', ru: 'Опыт', em: '📖' },
          { hanzi: '经验', pinyin: 'jīng yàn', ru: 'Опыт', em: '💡' },
          { hanzi: '景色', pinyin: 'jǐng sè', ru: 'Пейзаж', em: '🌄' },
          { hanzi: '警察', pinyin: 'jǐng chá', ru: 'Полиция', em: '👮' },
          { hanzi: '竞争', pinyin: 'jìng zhēng', ru: 'Конкуренция', em: '🏆' },
          { hanzi: '竟然', pinyin: 'jìng rán', ru: 'Неожиданно', em: '😮' },
          { hanzi: '镜子', pinyin: 'jìng zi', ru: 'Зеркало', em: '🪞' },
          { hanzi: '究竟', pinyin: 'jiū jìng', ru: 'В конце концов', em: '🤔' }
        ]
      },
      {
        id: 9,
        emoji: '🎉',
        title: 'J-L: Праздники и действия',
        cls: 'dc9',
        words: [
          { hanzi: '举办', pinyin: 'jǔ bàn', ru: 'Организовывать', em: '📋' },
          { hanzi: '举行', pinyin: 'jǔ xíng', ru: 'Проводить', em: '📋' },
          { hanzi: '拒绝', pinyin: 'jù jué', ru: 'Отказываться', em: '🚫' },
          { hanzi: '聚会', pinyin: 'jù huì', ru: 'Встреча', em: '🎉' },
          { hanzi: '距离', pinyin: 'jù lí', ru: 'Расстояние', em: '📏' },
          { hanzi: '开玩笑', pinyin: 'kāi wán xiào', ru: 'Шутить', em: '😂' },
          { hanzi: '开心', pinyin: 'kāi xīn', ru: 'Счастливый', em: '😄' },
          { hanzi: '看法', pinyin: 'kàn fǎ', ru: 'Мнение', em: '💭' },
          { hanzi: '烤鸭', pinyin: 'kǎo yā', ru: 'Утка по-пекински', em: '🦆' },
          { hanzi: '考虑', pinyin: 'kǎo lǜ', ru: 'Рассматривать', em: '🤔' },
          { hanzi: '棵', pinyin: 'kē', ru: 'Счётное слово (деревья)', em: '🌳' },
          { hanzi: '科学', pinyin: 'kē xué', ru: 'Наука', em: '🔬' },
          { hanzi: '咳嗽', pinyin: 'ké sou', ru: 'Кашлять', em: '🤧' },
          { hanzi: '可怜', pinyin: 'kě lián', ru: 'Жалкий', em: '🥺' },
          { hanzi: '可是', pinyin: 'kě shì', ru: 'Но', em: '🤔' },
          { hanzi: '可惜', pinyin: 'kě xī', ru: 'Жаль', em: '😔' },
          { hanzi: '客厅', pinyin: 'kè tīng', ru: 'Гостиная', em: '🛋️' },
          { hanzi: '肯定', pinyin: 'kěn dìng', ru: 'Уверенный', em: '👍' },
          { hanzi: '空', pinyin: 'kōng', ru: 'Пустой', em: '⬜' },
          { hanzi: '空气', pinyin: 'kōng qì', ru: 'Воздух', em: '🌬️' },
          { hanzi: '恐怕', pinyin: 'kǒng pà', ru: 'Бояться', em: '😨' },
          { hanzi: '矿泉水', pinyin: 'kuàng quán shuǐ', ru: 'Минеральная вода', em: '💧' },
          { hanzi: '困', pinyin: 'kùn', ru: 'Сонный', em: '😴' },
          { hanzi: '困难', pinyin: 'kùn nan', ru: 'Трудность', em: '🤯' },
          { hanzi: '垃圾桶', pinyin: 'lā jī tǒng', ru: 'Мусорное ведро', em: '🗑️' },
          { hanzi: '拉', pinyin: 'lā', ru: 'Тянуть', em: '🫸' },
          { hanzi: '辣', pinyin: 'là', ru: 'Острый', em: '🌶️' },
          { hanzi: '来不及', pinyin: 'lái bu jí', ru: 'Не успеть', em: '⏰' },
          { hanzi: '来得及', pinyin: 'lái de jí', ru: 'Успеть', em: '⏰' },
          { hanzi: '来自', pinyin: 'lái zì', ru: 'Из', em: '➡️' },
          { hanzi: '懒', pinyin: 'lǎn', ru: 'Ленивый', em: '😴' },
          { hanzi: '浪费', pinyin: 'làng fèi', ru: 'Тратить впустую', em: '💸' },
          { hanzi: '浪漫', pinyin: 'làng màn', ru: 'Романтичный', em: '💕' },
          { hanzi: '老虎', pinyin: 'lǎo hǔ', ru: 'Тигр', em: '🐯' },
          { hanzi: '冷静', pinyin: 'lěng jìng', ru: 'Спокойный', em: '😌' },
          { hanzi: '理发', pinyin: 'lǐ fà', ru: 'Стричься', em: '💇' },
          { hanzi: '理解', pinyin: 'lǐ jiě', ru: 'Понимать', em: '🧠' },
          { hanzi: '理想', pinyin: 'lǐ xiǎng', ru: 'Идеал', em: '🌟' },
          { hanzi: '礼拜天', pinyin: 'lǐ bài tiān', ru: 'Воскресенье', em: '📅' },
          { hanzi: '礼貌', pinyin: 'lǐ mào', ru: 'Вежливый', em: '🙏' },
          { hanzi: '例如', pinyin: 'lì rú', ru: 'Например', em: '📝' },
          { hanzi: '力气', pinyin: 'lì qì', ru: 'Сила', em: '💪' },
          { hanzi: '厉害', pinyin: 'lì hài', ru: 'Сильный', em: '💪' },
          { hanzi: '俩', pinyin: 'liǎ', ru: 'Двое', em: '2️⃣' },
          { hanzi: '联系', pinyin: 'lián xì', ru: 'Связываться', em: '📞' },
          { hanzi: '连', pinyin: 'lián', ru: 'Даже', em: '➕' },
          { hanzi: '凉快', pinyin: 'liáng kuai', ru: 'Прохладный', em: '❄️' },
          { hanzi: '零钱', pinyin: 'líng qián', ru: 'Мелочь', em: '🪙' },
          { hanzi: '另外', pinyin: 'lìng wài', ru: 'Кроме того', em: '➕' },
          { hanzi: '流利', pinyin: 'liú lì', ru: 'Беглый', em: '🗣️' },
          { hanzi: '流行', pinyin: 'liú xíng', ru: 'Популярный', em: '🔥' },
          { hanzi: '留', pinyin: 'liú', ru: 'Оставаться', em: '⏳' },
          { hanzi: '旅行', pinyin: 'lǚ xíng', ru: 'Путешествовать', em: '✈️' },
          { hanzi: '乱', pinyin: 'luàn', ru: 'Беспорядок', em: '🌀' },
          { hanzi: '律师', pinyin: 'lǜ shī', ru: 'Юрист', em: '⚖️' }
        ]
      },

      // ============================================================
      // ЧАСТЬ 5: M-Q (281-400)
      // ============================================================
      {
        id: 10,
        emoji: '😩',
        title: 'M: Состояния и чувства',
        cls: 'dc10',
        words: [
          { hanzi: '麻烦', pinyin: 'má fan', ru: 'Беспокоить', em: '😩' },
          { hanzi: '马虎', pinyin: 'mǎ hu', ru: 'Небрежный', em: '😅' },
          { hanzi: '慢', pinyin: 'màn', ru: 'Медленный', em: '🐢' },
          { hanzi: '毛', pinyin: 'máo', ru: 'Волосы', em: '💇' },
          { hanzi: '毛巾', pinyin: 'máo jīn', ru: 'Полотенце', em: '🧣' },
          { hanzi: '美丽', pinyin: 'měi lì', ru: 'Красивый', em: '✨' },
          { hanzi: '梦', pinyin: 'mèng', ru: 'Мечта', em: '💭' },
          { hanzi: '迷路', pinyin: 'mí lù', ru: 'Заблудиться', em: '😵' },
          { hanzi: '密码', pinyin: 'mì mǎ', ru: 'Пароль', em: '🔑' },
          { hanzi: '免费', pinyin: 'miǎn fèi', ru: 'Бесплатный', em: '🆓' },
          { hanzi: '秒', pinyin: 'miǎo', ru: 'Секунда', em: '⏱️' },
          { hanzi: '民族', pinyin: 'mín zú', ru: 'Нация', em: '🏳️' },
          { hanzi: '母亲', pinyin: 'mǔ qīn', ru: 'Мать', em: '👩' },
          { hanzi: '目的', pinyin: 'mù dì', ru: 'Цель', em: '🎯' }
        ]
      },
      {
        id: 11,
        emoji: '🤔',
        title: 'N: Вопросы и состояние',
        cls: 'dc11',
        words: [
          { hanzi: '耐心', pinyin: 'nài xīn', ru: 'Терпеливый', em: '🧘' },
          { hanzi: '难道', pinyin: 'nán dào', ru: 'Неужели', em: '🤔' },
          { hanzi: '难受', pinyin: 'nán shòu', ru: 'Плохо себя чувствовать', em: '🤒' },
          { hanzi: '内', pinyin: 'nèi', ru: 'Внутри', em: '🔲' },
          { hanzi: '内容', pinyin: 'nèi róng', ru: 'Содержание', em: '📋' },
          { hanzi: '能力', pinyin: 'néng lì', ru: 'Способность', em: '💪' },
          { hanzi: '年龄', pinyin: 'nián líng', ru: 'Возраст', em: '🎂' },
          { hanzi: '弄', pinyin: 'nòng', ru: 'Делать', em: '🔨' },
          { hanzi: '暖和', pinyin: 'nuǎn huo', ru: 'Тёплый', em: '☀️' }
        ]
      },
      {
        id: 12,
        emoji: '🔄',
        title: 'O-P: Время и действия',
        cls: 'dc12',
        words: [
          { hanzi: '偶尔', pinyin: 'ǒu ěr', ru: 'Иногда', em: '🔄' },
          { hanzi: '排队', pinyin: 'pái duì', ru: 'Стоять в очереди', em: '🚶' },
          { hanzi: '排列', pinyin: 'pái liè', ru: 'Расставлять', em: '📋' },
          { hanzi: '判断', pinyin: 'pàn duàn', ru: 'Судить', em: '⚖️' },
          { hanzi: '陪', pinyin: 'péi', ru: 'Сопровождать', em: '👥' },
          { hanzi: '批评', pinyin: 'pī píng', ru: 'Критиковать', em: '👎' },
          { hanzi: '皮肤', pinyin: 'pí fū', ru: 'Кожа', em: '🧴' },
          { hanzi: '脾气', pinyin: 'pí qi', ru: 'Характер', em: '😤' },
          { hanzi: '篇', pinyin: 'piān', ru: 'Счётное слово (статьи)', em: '📄' },
          { hanzi: '骗', pinyin: 'piàn', ru: 'Обманывать', em: '🤥' },
          { hanzi: '乒乓球', pinyin: 'pīng pāng qiú', ru: 'Настольный теннис', em: '🏓' },
          { hanzi: '平时', pinyin: 'píng shí', ru: 'Обычно', em: '🔄' },
          { hanzi: '破', pinyin: 'pò', ru: 'Рвать', em: '💔' },
          { hanzi: '葡萄', pinyin: 'pú tao', ru: 'Виноград', em: '🍇' },
          { hanzi: '普遍', pinyin: 'pǔ biàn', ru: 'Общий', em: '🌐' },
          { hanzi: '普通话', pinyin: 'pǔ tōng huà', ru: 'Путунхуа', em: '🗣️' }
        ]
      },
      {
        id: 13,
        emoji: '📋',
        title: 'Q: Вопросы и условия',
        cls: 'dc13',
        words: [
          { hanzi: '其次', pinyin: 'qí cì', ru: 'Затем', em: '➡️' },
          { hanzi: '其中', pinyin: 'qí zhōng', ru: 'Среди', em: '🔀' },
          { hanzi: '气候', pinyin: 'qì hòu', ru: 'Климат', em: '🌤️' },
          { hanzi: '千万', pinyin: 'qiān wàn', ru: 'Обязательно', em: '❗' },
          { hanzi: '签证', pinyin: 'qiān zhèng', ru: 'Виза', em: '🛂' },
          { hanzi: '敲', pinyin: 'qiāo', ru: 'Стучать', em: '🔨' },
          { hanzi: '桥', pinyin: 'qiáo', ru: 'Мост', em: '🌉' },
          { hanzi: '巧克力', pinyin: 'qiǎo kè lì', ru: 'Шоколад', em: '🍫' },
          { hanzi: '亲戚', pinyin: 'qīn qi', ru: 'Родственник', em: '👨‍👩‍👧' },
          { hanzi: '轻', pinyin: 'qīng', ru: 'Лёгкий', em: '🪶' },
          { hanzi: '轻松', pinyin: 'qīng sōng', ru: 'Легкий', em: '😌' },
          { hanzi: '情况', pinyin: 'qíng kuàng', ru: 'Ситуация', em: '📋' },
          { hanzi: '穷', pinyin: 'qióng', ru: 'Бедный', em: '😔' },
          { hanzi: '区别', pinyin: 'qū bié', ru: 'Разница', em: '⚖️' },
          { hanzi: '取', pinyin: 'qǔ', ru: 'Брать', em: '✋' },
          { hanzi: '全部', pinyin: 'quán bù', ru: 'Весь', em: '📦' },
          { hanzi: '缺点', pinyin: 'quē diǎn', ru: 'Недостаток', em: '👎' },
          { hanzi: '缺少', pinyin: 'quē shǎo', ru: 'Не хватать', em: '📉' },
          { hanzi: '却', pinyin: 'què', ru: 'Однако', em: '🤔' },
          { hanzi: '确实', pinyin: 'què shí', ru: 'Действительно', em: '💯' }
        ]
      },

      // ============================================================
      // ЧАСТЬ 6: R-S (401-500)
      // ============================================================
      {
        id: 14,
        emoji: '🔥',
        title: 'R-S: Состояния и погода',
        cls: 'dc14',
        words: [
          { hanzi: '然而', pinyin: 'rán ér', ru: 'Однако', em: '🤔' },
          { hanzi: '热闹', pinyin: 'rè nao', ru: 'Оживлённый', em: '🎉' },
          { hanzi: '任何', pinyin: 'rèn hé', ru: 'Любой', em: '🔢' },
          { hanzi: '任务', pinyin: 'rèn wu', ru: 'Задание', em: '📋' },
          { hanzi: '扔', pinyin: 'rēng', ru: 'Бросать', em: '🗑️' },
          { hanzi: '仍然', pinyin: 'réng rán', ru: 'Всё ещё', em: '🔄' },
          { hanzi: '日记', pinyin: 'rì jì', ru: 'Дневник', em: '📖' },
          { hanzi: '入口', pinyin: 'rù kǒu', ru: 'Вход', em: '🚪' },
          { hanzi: '散步', pinyin: 'sàn bù', ru: 'Гулять', em: '🚶' },
          { hanzi: '森林', pinyin: 'sēn lín', ru: 'Лес', em: '🌳' },
          { hanzi: '沙发', pinyin: 'shā fā', ru: 'Диван', em: '🛋️' },
          { hanzi: '伤心', pinyin: 'shāng xīn', ru: 'Печальный', em: '😢' },
          { hanzi: '商量', pinyin: 'shāng liang', ru: 'Обсуждать', em: '💬' },
          { hanzi: '稍微', pinyin: 'shāo wēi', ru: 'Немного', em: '🤏' },
          { hanzi: '勺子', pinyin: 'sháo zi', ru: 'Ложка', em: '🥄' },
          { hanzi: '社会', pinyin: 'shè huì', ru: 'Общество', em: '👥' },
          { hanzi: '深', pinyin: 'shēn', ru: 'Глубокий', em: '⬇️' },
          { hanzi: '申请', pinyin: 'shēn qǐng', ru: 'Подавать заявку', em: '📝' },
          { hanzi: '甚至', pinyin: 'shèn zhì', ru: 'Даже', em: '➕' },
          { hanzi: '生活', pinyin: 'shēng huó', ru: 'Жизнь', em: '🌿' },
          { hanzi: '生命', pinyin: 'shēng mìng', ru: 'Жизнь', em: '🌱' },
          { hanzi: '生意', pinyin: 'shēng yì', ru: 'Бизнес', em: '💼' },
          { hanzi: '省', pinyin: 'shěng', ru: 'Провинция', em: '🗺️' },
          { hanzi: '剩', pinyin: 'shèng', ru: 'Оставаться', em: '⏳' },
          { hanzi: '失败', pinyin: 'shī bài', ru: 'Провал', em: '😞' },
          { hanzi: '失望', pinyin: 'shī wàng', ru: 'Разочаровываться', em: '😞' },
          { hanzi: '师傅', pinyin: 'shī fu', ru: 'Мастер', em: '🧑‍🏫' },
          { hanzi: '十分', pinyin: 'shí fēn', ru: 'Очень', em: '💪' },
          { hanzi: '实际', pinyin: 'shí jì', ru: 'Фактический', em: '📊' },
          { hanzi: '实在', pinyin: 'shí zài', ru: 'На самом деле', em: '💯' },
          { hanzi: '使', pinyin: 'shǐ', ru: 'Заставлять', em: '💪' },
          { hanzi: '使用', pinyin: 'shǐ yòng', ru: 'Использовать', em: '🔧' },
          { hanzi: '世纪', pinyin: 'shì jì', ru: 'Век', em: '📅' },
          { hanzi: '是否', pinyin: 'shì fǒu', ru: 'Ли', em: '❓' },
          { hanzi: '适合', pinyin: 'shì hé', ru: 'Подходить', em: '👍' },
          { hanzi: '适应', pinyin: 'shì yìng', ru: 'Адаптироваться', em: '🔄' },
          { hanzi: '收', pinyin: 'shōu', ru: 'Получать', em: '📥' },
          { hanzi: '收入', pinyin: 'shōu rù', ru: 'Доход', em: '💰' },
          { hanzi: '收拾', pinyin: 'shōu shi', ru: 'Убирать', em: '🧹' },
          { hanzi: '首都', pinyin: 'shǒu dū', ru: 'Столица', em: '🏛️' },
          { hanzi: '首先', pinyin: 'shǒu xiān', ru: 'Во-первых', em: '1️⃣' },
          { hanzi: '受不了', pinyin: 'shòu bù liǎo', ru: 'Не выносить', em: '😫' },
          { hanzi: '受到', pinyin: 'shòu dào', ru: 'Получать', em: '📥' },
          { hanzi: '售货员', pinyin: 'shòu huò yuán', ru: 'Продавец', em: '🛒' },
          { hanzi: '输', pinyin: 'shū', ru: 'Проигрывать', em: '😞' },
          { hanzi: '熟悉', pinyin: 'shú xī', ru: 'Быть знакомым', em: '🤝' },
          { hanzi: '数量', pinyin: 'shù liàng', ru: 'Количество', em: '🔢' },
          { hanzi: '数字', pinyin: 'shù zì', ru: 'Цифра', em: '🔢' },
          { hanzi: '帅', pinyin: 'shuài', ru: 'Красивый', em: '😎' },
          { hanzi: '顺便', pinyin: 'shùn biàn', ru: 'Заодно', em: '🔄' },
          { hanzi: '顺利', pinyin: 'shùn lì', ru: 'Гладко', em: '✅' },
          { hanzi: '顺序', pinyin: 'shùn xù', ru: 'Порядок', em: '🔢' },
          { hanzi: '说明', pinyin: 'shuō míng', ru: 'Объяснять', em: '💡' },
          { hanzi: '硕士', pinyin: 'shuò shì', ru: 'Магистр', em: '🎓' },
          { hanzi: '死', pinyin: 'sǐ', ru: 'Умирать', em: '💀' },
          { hanzi: '塑料袋', pinyin: 'sù liào dài', ru: 'Пакет', em: '🛍️' },
          { hanzi: '速度', pinyin: 'sù dù', ru: 'Скорость', em: '🏃' },
          { hanzi: '酸', pinyin: 'suān', ru: 'Кислый', em: '🍋' },
          { hanzi: '随便', pinyin: 'suí biàn', ru: 'Как угодно', em: '🤷' },
          { hanzi: '随着', pinyin: 'suí zhe', ru: 'Вместе с', em: '👥' },
          { hanzi: '孙子', pinyin: 'sūn zi', ru: 'Внук', em: '👴' },
          { hanzi: '所有', pinyin: 'suǒ yǒu', ru: 'Все', em: '📦' }
        ]
      },

      // ============================================================
      // ЧАСТЬ 7: T-X (501-580)
      // ============================================================
      {
        id: 15,
        emoji: '📐',
        title: 'T: Техника и действия',
        cls: 'dc15',
        words: [
          { hanzi: '台', pinyin: 'tái', ru: 'Счётное слово (техника)', em: '📺' },
          { hanzi: '抬', pinyin: 'tái', ru: 'Поднимать', em: '⬆️' },
          { hanzi: '态度', pinyin: 'tài dù', ru: 'Отношение', em: '💭' },
          { hanzi: '弹钢琴', pinyin: 'tán gāng qín', ru: 'Играть на пианино', em: '🎹' },
          { hanzi: '谈', pinyin: 'tán', ru: 'Говорить', em: '🗣️' },
          { hanzi: '汤', pinyin: 'tāng', ru: 'Суп', em: '🍲' },
          { hanzi: '糖', pinyin: 'táng', ru: 'Конфета', em: '🍬' },
          { hanzi: '躺', pinyin: 'tǎng', ru: 'Лежать', em: '🛌' },
          { hanzi: '趟', pinyin: 'tàng', ru: 'Раз (поездка)', em: '🔢' },
          { hanzi: '讨论', pinyin: 'tǎo lùn', ru: 'Обсуждать', em: '💬' },
          { hanzi: '讨厌', pinyin: 'tǎo yàn', ru: 'Ненавидеть', em: '🤮' },
          { hanzi: '特点', pinyin: 'tè diǎn', ru: 'Особенность', em: '⭐' },
          { hanzi: '提', pinyin: 'tí', ru: 'Поднимать', em: '⬆️' },
          { hanzi: '提供', pinyin: 'tí gōng', ru: 'Предоставлять', em: '📤' },
          { hanzi: '提前', pinyin: 'tí qián', ru: 'Заранее', em: '⏰' },
          { hanzi: '提醒', pinyin: 'tí xǐng', ru: 'Напоминать', em: '🔔' },
          { hanzi: '填空', pinyin: 'tián kòng', ru: 'Заполнять', em: '📝' },
          { hanzi: '条件', pinyin: 'tiáo jiàn', ru: 'Условие', em: '📋' },
          { hanzi: '停', pinyin: 'tíng', ru: 'Останавливаться', em: '⏹️' },
          { hanzi: '挺', pinyin: 'tǐng', ru: 'Довольно', em: '👍' },
          { hanzi: '通过', pinyin: 'tōng guò', ru: 'Через', em: '➡️' },
          { hanzi: '通知', pinyin: 'tōng zhī', ru: 'Уведомлять', em: '📢' },
          { hanzi: '同情', pinyin: 'tóng qíng', ru: 'Сочувствовать', em: '🤝' },
          { hanzi: '同时', pinyin: 'tóng shí', ru: 'В то же время', em: '⏰' },
          { hanzi: '推', pinyin: 'tuī', ru: 'Толкать', em: '🫸' },
          { hanzi: '推迟', pinyin: 'tuī chí', ru: 'Откладывать', em: '⏰' },
          { hanzi: '脱', pinyin: 'tuō', ru: 'Снимать', em: '👕' }
        ]
      },
      {
        id: 16,
        emoji: '🌐',
        title: 'W-X: Интернет и культура',
        cls: 'dc16',
        words: [
          { hanzi: '袜子', pinyin: 'wà zi', ru: 'Носки', em: '🧦' },
          { hanzi: '完全', pinyin: 'wán quán', ru: 'Полностью', em: '💯' },
          { hanzi: '往往', pinyin: 'wǎng wǎng', ru: 'Часто', em: '🔄' },
          { hanzi: '网球', pinyin: 'wǎng qiú', ru: 'Теннис', em: '🎾' },
          { hanzi: '网站', pinyin: 'wǎng zhàn', ru: 'Сайт', em: '🌐' },
          { hanzi: '危险', pinyin: 'wēi xiǎn', ru: 'Опасный', em: '⚠️' },
          { hanzi: '卫生间', pinyin: 'wèi shēng jiān', ru: 'Ванная', em: '🚻' },
          { hanzi: '味道', pinyin: 'wèi dào', ru: 'Вкус', em: '👅' },
          { hanzi: '温度', pinyin: 'wēn dù', ru: 'Температура', em: '🌡️' },
          { hanzi: '文章', pinyin: 'wén zhāng', ru: 'Статья', em: '📰' },
          { hanzi: '污染', pinyin: 'wū rǎn', ru: 'Загрязнять', em: '☣️' },
          { hanzi: '无', pinyin: 'wú', ru: 'Без', em: '🚫' },
          { hanzi: '无聊', pinyin: 'wú liáo', ru: 'Скучный', em: '😴' },
          { hanzi: '无论', pinyin: 'wú lùn', ru: 'Независимо от', em: '🤷' },
          { hanzi: '误会', pinyin: 'wù huì', ru: 'Недоразумение', em: '😕' },
          { hanzi: '吸引', pinyin: 'xī yǐn', ru: 'Привлекать', em: '🧲' },
          { hanzi: '西红柿', pinyin: 'xī hóng shì', ru: 'Помидор', em: '🍅' },
          { hanzi: '咸', pinyin: 'xián', ru: 'Солёный', em: '🧂' },
          { hanzi: '现金', pinyin: 'xiàn jīn', ru: 'Наличные', em: '💰' },
          { hanzi: '羡慕', pinyin: 'xiàn mù', ru: 'Завидовать', em: '😍' },
          { hanzi: '相反', pinyin: 'xiāng fǎn', ru: 'Наоборот', em: '🔄' },
          { hanzi: '相同', pinyin: 'xiāng tóng', ru: 'Одинаковый', em: '🔄' },
          { hanzi: '香', pinyin: 'xiāng', ru: 'Ароматный', em: '🌸' },
          { hanzi: '详细', pinyin: 'xiáng xì', ru: 'Подробный', em: '📋' },
          { hanzi: '橡皮', pinyin: 'xiàng pí', ru: 'Ластик', em: '🧹' },
          { hanzi: '消息', pinyin: 'xiāo xi', ru: 'Новость', em: '📰' },
          { hanzi: '小吃', pinyin: 'xiǎo chī', ru: 'Закуска', em: '🍢' },
          { hanzi: '小伙子', pinyin: 'xiǎo huǒ zi', ru: 'Парень', em: '🧑' },
          { hanzi: '小说', pinyin: 'xiǎo shuō', ru: 'Роман', em: '📖' },
          { hanzi: '效果', pinyin: 'xiào guǒ', ru: 'Эффект', em: '💫' },
          { hanzi: '笑话', pinyin: 'xiào huà', ru: 'Шутка', em: '😂' },
          { hanzi: '心情', pinyin: 'xīn qíng', ru: 'Настроение', em: '💭' },
          { hanzi: '辛苦', pinyin: 'xīn kǔ', ru: 'Тяжёлый', em: '😓' },
          { hanzi: '信封', pinyin: 'xìn fēng', ru: 'Конверт', em: '✉️' },
          { hanzi: '信息', pinyin: 'xìn xī', ru: 'Информация', em: 'ℹ️' },
          { hanzi: '信心', pinyin: 'xìn xīn', ru: 'Уверенность', em: '💪' },
          { hanzi: '兴奋', pinyin: 'xīng fèn', ru: 'Взволнованный', em: '🤩' },
          { hanzi: '行', pinyin: 'xíng', ru: 'Идти', em: '🚶' },
          { hanzi: '醒', pinyin: 'xǐng', ru: 'Просыпаться', em: '😴' },
          { hanzi: '性别', pinyin: 'xìng bié', ru: 'Пол', em: '⚥' },
          { hanzi: '性格', pinyin: 'xìng gé', ru: 'Характер', em: '🧠' },
          { hanzi: '幸福', pinyin: 'xìng fú', ru: 'Счастливый', em: '😊' },
          { hanzi: '修理', pinyin: 'xiū lǐ', ru: 'Ремонтировать', em: '🔧' },
          { hanzi: '许多', pinyin: 'xǔ duō', ru: 'Много', em: '📚' },
          { hanzi: '学期', pinyin: 'xué qī', ru: 'Семестр', em: '📚' }
        ]
      },

      // ============================================================
      // ЧАСТЬ 8: Y-Z (581-600+)
      // ============================================================
      {
        id: 17,
        emoji: '📝',
        title: 'Y: Язык и культура',
        cls: 'dc17',
        words: [
          { hanzi: '压力', pinyin: 'yā lì', ru: 'Давление', em: '💪' },
          { hanzi: '牙膏', pinyin: 'yá gāo', ru: 'Зубная паста', em: '🪥' },
          { hanzi: '呀', pinyin: 'ya', ru: 'Частица', em: '💬' },
          { hanzi: '严格', pinyin: 'yán gé', ru: 'Строгий', em: '📏' },
          { hanzi: '严重', pinyin: 'yán zhòng', ru: 'Серьёзный', em: '⚠️' },
          { hanzi: '盐', pinyin: 'yán', ru: 'Соль', em: '🧂' },
          { hanzi: '眼镜', pinyin: 'yǎn jìng', ru: 'Очки', em: '👓' },
          { hanzi: '演出', pinyin: 'yǎn chū', ru: 'Выступление', em: '🎭' },
          { hanzi: '演员', pinyin: 'yǎn yuán', ru: 'Актёр', em: '🎭' },
          { hanzi: '养成', pinyin: 'yǎng chéng', ru: 'Приобретать', em: '🌱' },
          { hanzi: '阳光', pinyin: 'yáng guāng', ru: 'Солнечный свет', em: '☀️' },
          { hanzi: '样子', pinyin: 'yàng zi', ru: 'Вид', em: '👀' },
          { hanzi: '邀请', pinyin: 'yāo qǐng', ru: 'Приглашать', em: '📩' },
          { hanzi: '要是', pinyin: 'yào shi', ru: 'Если', em: '🤔' },
          { hanzi: '钥匙', pinyin: 'yào shi', ru: 'Ключ', em: '🔑' },
          { hanzi: '也许', pinyin: 'yě xǔ', ru: 'Может быть', em: '🤷' },
          { hanzi: '叶子', pinyin: 'yè zi', ru: 'Лист', em: '🍃' },
          { hanzi: '页', pinyin: 'yè', ru: 'Страница', em: '📄' },
          { hanzi: '一切', pinyin: 'yī qiè', ru: 'Всё', em: '📦' },
          { hanzi: '以', pinyin: 'yǐ', ru: 'С помощью', em: '🔧' },
          { hanzi: '以为', pinyin: 'yǐ wéi', ru: 'Думать', em: '💭' },
          { hanzi: '艺术', pinyin: 'yì shù', ru: 'Искусство', em: '🎨' },
          { hanzi: '意见', pinyin: 'yì jiàn', ru: 'Мнение', em: '💭' },
          { hanzi: '因此', pinyin: 'yīn cǐ', ru: 'Поэтому', em: '➡️' },
          { hanzi: '引起', pinyin: 'yǐn qǐ', ru: 'Вызывать', em: '🔥' },
          { hanzi: '印象', pinyin: 'yìn xiàng', ru: 'Впечатление', em: '💭' },
          { hanzi: '应聘', pinyin: 'yìng pìn', ru: 'Подавать заявление', em: '📝' },
          { hanzi: '赢', pinyin: 'yíng', ru: 'Выигрывать', em: '🏆' },
          { hanzi: '影响', pinyin: 'yǐng xiǎng', ru: 'Влиять', em: '💫' },
          { hanzi: '永远', pinyin: 'yǒng yuǎn', ru: 'Навсегда', em: '♾️' },
          { hanzi: '勇敢', pinyin: 'yǒng gǎn', ru: 'Храбрый', em: '🦁' },
          { hanzi: '优点', pinyin: 'yōu diǎn', ru: 'Достоинство', em: '👍' },
          { hanzi: '幽默', pinyin: 'yōu mò', ru: 'Юмор', em: '😂' },
          { hanzi: '尤其', pinyin: 'yóu qí', ru: 'Особенно', em: '⭐' },
          { hanzi: '由', pinyin: 'yóu', ru: 'Из', em: '➡️' },
          { hanzi: '由于', pinyin: 'yóu yú', ru: 'Из-за', em: '📋' },
          { hanzi: '邮局', pinyin: 'yóu jú', ru: 'Почта', em: '📮' },
          { hanzi: '友好', pinyin: 'yǒu hǎo', ru: 'Дружелюбный', em: '😊' },
          { hanzi: '友谊', pinyin: 'yǒu yì', ru: 'Дружба', em: '🤝' },
          { hanzi: '有趣', pinyin: 'yǒu qù', ru: 'Интересный', em: '🤔' },
          { hanzi: '于是', pinyin: 'yú shì', ru: 'Таким образом', em: '➡️' },
          { hanzi: '与', pinyin: 'yǔ', ru: 'С', em: '👥' },
          { hanzi: '语法', pinyin: 'yǔ fǎ', ru: 'Грамматика', em: '📝' },
          { hanzi: '语言', pinyin: 'yǔ yán', ru: 'Язык', em: '🗣️' },
          { hanzi: '预习', pinyin: 'yù xí', ru: 'Готовиться', em: '📚' },
          { hanzi: '原来', pinyin: 'yuán lái', ru: 'Оказывается', em: '💡' },
          { hanzi: '原谅', pinyin: 'yuán liàng', ru: 'Прощать', em: '🙏' },
          { hanzi: '原因', pinyin: 'yuán yīn', ru: 'Причина', em: '📋' },
          { hanzi: '约会', pinyin: 'yuē huì', ru: 'Встреча', em: '💕' },
          { hanzi: '阅读', pinyin: 'yuè dú', ru: 'Читать', em: '📖' },
          { hanzi: '云', pinyin: 'yún', ru: 'Облако', em: '☁️' },
          { hanzi: '允许', pinyin: 'yǔn xǔ', ru: 'Разрешать', em: '✅' },
          { hanzi: '愉快', pinyin: 'yú kuài', ru: 'Приятный', em: '😊' }
        ]
      },
      {
        id: 18,
        emoji: '🏁',
        title: 'Z: Финальные слова',
        cls: 'dc18',
        words: [
          { hanzi: '咱们', pinyin: 'zán men', ru: 'Мы', em: '👥' },
          { hanzi: '暂时', pinyin: 'zàn shí', ru: 'Временно', em: '⏳' },
          { hanzi: '杂志', pinyin: 'zá zhì', ru: 'Журнал', em: '📰' },
          { hanzi: '脏', pinyin: 'zāng', ru: 'Грязный', em: '💩' },
          { hanzi: '责任', pinyin: 'zé rèn', ru: 'Ответственность', em: '💼' },
          { hanzi: '增加', pinyin: 'zēng jiā', ru: 'Увеличивать', em: '📈' },
          { hanzi: '占线', pinyin: 'zhàn xiàn', ru: 'Занято', em: '📞' },
          { hanzi: '张', pinyin: 'zhāng', ru: 'Счётное слово', em: '📄' },
          { hanzi: '招聘', pinyin: 'zhāo pìn', ru: 'Набирать', em: '📢' },
          { hanzi: '着急', pinyin: 'zháo jí', ru: 'Спешить', em: '🏃' },
          { hanzi: '照', pinyin: 'zhào', ru: 'Фотографировать', em: '📸' },
          { hanzi: '照顾', pinyin: 'zhào gù', ru: 'Заботиться', em: '🤗' },
          { hanzi: '照片', pinyin: 'zhào piàn', ru: 'Фото', em: '📸' },
          { hanzi: '哲学', pinyin: 'zhé xué', ru: 'Философия', em: '🧠' },
          { hanzi: '这', pinyin: 'zhè', ru: 'Этот', em: '👈' },
          { hanzi: '真诚', pinyin: 'zhēn chéng', ru: 'Искренний', em: '❤️' },
          { hanzi: '真正', pinyin: 'zhēn zhèng', ru: 'Настоящий', em: '💯' },
          { hanzi: '政策', pinyin: 'zhèng cè', ru: 'Политика', em: '📋' },
          { hanzi: '正确', pinyin: 'zhèng què', ru: 'Правильный', em: '✅' },
          { hanzi: '整理', pinyin: 'zhěng lǐ', ru: 'Упорядочивать', em: '🧹' },
          { hanzi: '正常', pinyin: 'zhèng cháng', ru: 'Нормальный', em: '👍' },
          { hanzi: '正式', pinyin: 'zhèng shì', ru: 'Официальный', em: '📋' },
          { hanzi: '证明', pinyin: 'zhèng míng', ru: 'Доказывать', em: '📄' },
          { hanzi: '之', pinyin: 'zhī', ru: 'Частица', em: '🔗' },
          { hanzi: '支持', pinyin: 'zhī chí', ru: 'Поддерживать', em: '🤝' },
          { hanzi: '知识', pinyin: 'zhī shi', ru: 'Знание', em: '📚' },
          { hanzi: '直接', pinyin: 'zhí jiē', ru: 'Прямой', em: '➡️' },
          { hanzi: '值得', pinyin: 'zhí de', ru: 'Стоить', em: '💰' },
          { hanzi: '职业', pinyin: 'zhí yè', ru: 'Профессия', em: '💼' },
          { hanzi: '植物', pinyin: 'zhí wù', ru: 'Растение', em: '🌱' },
          { hanzi: '只好', pinyin: 'zhǐ hǎo', ru: 'Приходится', em: '😤' },
          { hanzi: '只要', pinyin: 'zhǐ yào', ru: 'Если только', em: '🔒' },
          { hanzi: '指', pinyin: 'zhǐ', ru: 'Указывать', em: '👉' },
          { hanzi: '至少', pinyin: 'zhì shǎo', ru: 'По крайней мере', em: '🔢' },
          { hanzi: '质量', pinyin: 'zhì liàng', ru: 'Качество', em: '⭐' },
          { hanzi: '重', pinyin: 'zhòng', ru: 'Тяжёлый', em: '⚖️' },
          { hanzi: '重点', pinyin: 'zhòng diǎn', ru: 'Основной момент', em: '🎯' },
          { hanzi: '重视', pinyin: 'zhòng shì', ru: 'Придавать значение', em: '⭐' },
          { hanzi: '周围', pinyin: 'zhōu wéi', ru: 'Окрестности', em: '🌍' },
          { hanzi: '主要', pinyin: 'zhǔ yào', ru: 'Главный', em: '⭐' },
          { hanzi: '主意', pinyin: 'zhǔ yì', ru: 'Идея', em: '💡' },
          { hanzi: '著名', pinyin: 'zhù míng', ru: 'Известный', em: '⭐' },
          { hanzi: '祝贺', pinyin: 'zhù hè', ru: 'Поздравлять', em: '🎉' },
          { hanzi: '转', pinyin: 'zhuǎn', ru: 'Поворачивать', em: '🔄' },
          { hanzi: '赚', pinyin: 'zhuàn', ru: 'Зарабатывать', em: '💰' },
          { hanzi: '专业', pinyin: 'zhuān yè', ru: 'Специальность', em: '🎓' },
          { hanzi: '准时', pinyin: 'zhǔn shí', ru: 'Вовремя', em: '⏰' },
          { hanzi: '准确', pinyin: 'zhǔn què', ru: 'Точный', em: '🎯' },
          { hanzi: '仔细', pinyin: 'zǐ xì', ru: 'Внимательный', em: '🔍' },
          { hanzi: '自然', pinyin: 'zì rán', ru: 'Природа', em: '🌿' },
          { hanzi: '自信', pinyin: 'zì xìn', ru: 'Уверенный', em: '💪' },
          { hanzi: '总结', pinyin: 'zǒng jié', ru: 'Суммировать', em: '📋' },
          { hanzi: '租', pinyin: 'zū', ru: 'Арендовать', em: '🏠' },
          { hanzi: '尊重', pinyin: 'zūn zhòng', ru: 'Уважать', em: '🙏' },
          { hanzi: '座位', pinyin: 'zuò wèi', ru: 'Место', em: '💺' },
          { hanzi: '座', pinyin: 'zuò', ru: 'Счётное слово', em: '🏔️' },
          { hanzi: '作家', pinyin: 'zuò jiā', ru: 'Писатель', em: '✍️' },
          { hanzi: '作用', pinyin: 'zuò yòng', ru: 'Роль', em: '🎯' },
          { hanzi: '作者', pinyin: 'zuò zhě', ru: 'Автор', em: '✍️' },
          { hanzi: '左右', pinyin: 'zuǒ yòu', ru: 'Около', em: '🔢' }
        ]
      }
    ]
  },

  // ========== Остальные уровни ==========
  hsk5: { label: 'HSK 5', decks: [] },
  hsk6: { label: 'HSK 6', decks: [] }
};

